//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class Admin_Page : Neo.ApplicationFramework.Controls.Controls.Form, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage {
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Logo;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Back_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_prewashWaterTime_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_cleaningRestTime_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_dryingAirTime_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_dryingRestTime_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_cleaningWaterTime_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_cleaningPressTime_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_prewashRestTime_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_prewashWaterTime_Num;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_prewashRestTime_Num;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_dryingAirTime_Num;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_dryingRestTime_Num;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_cleaningWaterTime_Num;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_cleaningPressTime_Num;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_cleaningRestTime_Num;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Warning_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_testTime_Num;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_TestTime_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric;
        
        private bool m_Initialized_Admin_Page;
        
        public Admin_Page() {
            this.InitializeComponent();
            this.m_Back_Button.Click += new System.EventHandler(this.m_Back_Button_Action_Click);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Logo {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Logo);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Back_Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Back_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter prewashWaterTime_Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_prewashWaterTime_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter cleaningRestTime_Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_cleaningRestTime_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter dryingAirTime_Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_dryingAirTime_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter dryingRestTime_Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_dryingRestTime_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter cleaningWaterTime_Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_cleaningWaterTime_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter cleaningPressTime_Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_cleaningPressTime_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter prewashRestTime_Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_prewashRestTime_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter prewashWaterTime_Num {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_prewashWaterTime_Num);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter prewashRestTime_Num {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_prewashRestTime_Num);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter dryingAirTime_Num {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_dryingAirTime_Num);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter dryingRestTime_Num {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_dryingRestTime_Num);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter cleaningWaterTime_Num {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_cleaningWaterTime_Num);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter cleaningPressTime_Num {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_cleaningPressTime_Num);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter cleaningRestTime_Num {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_cleaningRestTime_Num);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Warning_Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Warning_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter testTime_Num {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_testTime_Num);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter TestTime_Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_TestTime_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric);
            }
        }
        
        private void InitializeComponent() {
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            this.m_Logo = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Back_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_prewashWaterTime_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_cleaningRestTime_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_dryingAirTime_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_dryingRestTime_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_cleaningWaterTime_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_cleaningPressTime_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_prewashRestTime_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_prewashWaterTime_Num = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_prewashRestTime_Num = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_dryingAirTime_Num = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_dryingRestTime_Num = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_cleaningWaterTime_Num = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_cleaningPressTime_Num = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_cleaningRestTime_Num = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_Warning_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_testTime_Num = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_TestTime_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_AnalogNumeric = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            ((System.ComponentModel.ISupportInitialize)(this.m_Logo)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Back_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_prewashWaterTime_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_cleaningRestTime_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_dryingAirTime_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_dryingRestTime_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_cleaningWaterTime_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_cleaningPressTime_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_prewashRestTime_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_prewashWaterTime_Num)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_prewashRestTime_Num)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_dryingAirTime_Num)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_dryingRestTime_Num)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_cleaningWaterTime_Num)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_cleaningPressTime_Num)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_cleaningRestTime_Num)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Warning_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_testTime_Num)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_TestTime_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric)).BeginInit();
            this.SuspendLayout();
            // 
            // Admin_Page
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(130)))), ((int)(((byte)(31))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.ThreeDBorder;
            this.ControlBox = false;
            // 
            // m_Logo
            // 
            this.m_Logo.BlinkDynamicsValue = false;
            this.m_Logo.DelayMouseInputPeriod = 0;
            this.m_Logo.EnabledDynamicsValue = true;
            this.m_Logo.Height = 482;
            this.m_Logo.Left = 464;
            this.m_Logo.Name = "m_Logo";
            this.m_Logo.ScreenOwnerName = "Admin_Page";
            this.m_Logo.Stretch = true;
            this.m_Logo.SymbolName = "logobeyaz";
            this.m_Logo.Top = 17;
            this.m_Logo.VisibleDynamicsValue = true;
            this.m_Logo.Width = 475;
            // 
            // m_Back_Button
            // 
            this.m_Back_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(49)))), ((int)(((byte)(146))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Back_Button.BlinkDynamicsValue = false;
            this.m_Back_Button.Bold = true;
            this.m_Back_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Back_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3D, 3D, 3D, 3D);
            this.m_Back_Button.DelayMouseInputPeriod = 0;
            this.m_Back_Button.EnabledDynamicsValue = true;
            this.m_Back_Button.FontSizePixels = 16;
            this.m_Back_Button.ForceTransparency = true;
            this.m_Back_Button.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Back_Button.Height = 50;
            this.m_Back_Button.IndicatorMargin = null;
            this.m_Back_Button.Left = 10;
            this.m_Back_Button.Name = "m_Back_Button";
            this.m_Back_Button.RequiresTransparency = true;
            this.m_Back_Button.ScreenOwnerName = "Admin_Page";
            this.m_Back_Button.StyleName = "Chrome";
            this.m_Back_Button.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_Back_Button.TextHeight = 19;
            this.m_Back_Button.TextValue = 0D;
            this.m_Back_Button.TextWidth = 94;
            this.m_Back_Button.Top = 10;
            this.m_Back_Button.Value = 0D;
            this.m_Back_Button.VisibleDynamicsValue = true;
            this.m_Back_Button.VisualPropertiesHashCode = 1859279993;
            this.m_Back_Button.Width = 100;
            // 
            // m_prewashWaterTime_Text
            // 
            this.m_prewashWaterTime_Text.AutoSize = false;
            this.m_prewashWaterTime_Text.BlinkDynamicsValue = false;
            this.m_prewashWaterTime_Text.Bold = true;
            this.m_prewashWaterTime_Text.DelayMouseInputPeriod = 0;
            this.m_prewashWaterTime_Text.EnabledDynamicsValue = true;
            this.m_prewashWaterTime_Text.FontSizePixels = 22;
            this.m_prewashWaterTime_Text.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_prewashWaterTime_Text.Height = 35;
            this.m_prewashWaterTime_Text.Left = 10;
            this.m_prewashWaterTime_Text.Name = "m_prewashWaterTime_Text";
            this.m_prewashWaterTime_Text.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5.5D, 0D, 5.5D, 1D);
            this.m_prewashWaterTime_Text.ScreenOwnerName = "Admin_Page";
            this.m_prewashWaterTime_Text.TextVerticalAlignment = "Center";
            this.m_prewashWaterTime_Text.Top = 66;
            this.m_prewashWaterTime_Text.VisibleDynamicsValue = true;
            this.m_prewashWaterTime_Text.Width = 585;
            // 
            // m_cleaningRestTime_Text
            // 
            this.m_cleaningRestTime_Text.AutoSize = false;
            this.m_cleaningRestTime_Text.BlinkDynamicsValue = false;
            this.m_cleaningRestTime_Text.Bold = true;
            this.m_cleaningRestTime_Text.DelayMouseInputPeriod = 0;
            this.m_cleaningRestTime_Text.EnabledDynamicsValue = true;
            this.m_cleaningRestTime_Text.FontSizePixels = 22;
            this.m_cleaningRestTime_Text.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_cleaningRestTime_Text.Height = 35;
            this.m_cleaningRestTime_Text.Left = 10;
            this.m_cleaningRestTime_Text.Name = "m_cleaningRestTime_Text";
            this.m_cleaningRestTime_Text.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5.5D, 0D, 5.5D, 1D);
            this.m_cleaningRestTime_Text.ScreenOwnerName = "Admin_Page";
            this.m_cleaningRestTime_Text.TextVerticalAlignment = "Center";
            this.m_cleaningRestTime_Text.Top = 360;
            this.m_cleaningRestTime_Text.VisibleDynamicsValue = true;
            this.m_cleaningRestTime_Text.Width = 585;
            // 
            // m_dryingAirTime_Text
            // 
            this.m_dryingAirTime_Text.AutoSize = false;
            this.m_dryingAirTime_Text.BlinkDynamicsValue = false;
            this.m_dryingAirTime_Text.Bold = true;
            this.m_dryingAirTime_Text.DelayMouseInputPeriod = 0;
            this.m_dryingAirTime_Text.EnabledDynamicsValue = true;
            this.m_dryingAirTime_Text.FontSizePixels = 22;
            this.m_dryingAirTime_Text.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_dryingAirTime_Text.Height = 35;
            this.m_dryingAirTime_Text.Left = 10;
            this.m_dryingAirTime_Text.Name = "m_dryingAirTime_Text";
            this.m_dryingAirTime_Text.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5.5D, 0D, 5.5D, 1D);
            this.m_dryingAirTime_Text.ScreenOwnerName = "Admin_Page";
            this.m_dryingAirTime_Text.TextVerticalAlignment = "Center";
            this.m_dryingAirTime_Text.Top = 164;
            this.m_dryingAirTime_Text.VisibleDynamicsValue = true;
            this.m_dryingAirTime_Text.Width = 585;
            // 
            // m_dryingRestTime_Text
            // 
            this.m_dryingRestTime_Text.AutoSize = false;
            this.m_dryingRestTime_Text.BlinkDynamicsValue = false;
            this.m_dryingRestTime_Text.Bold = true;
            this.m_dryingRestTime_Text.DelayMouseInputPeriod = 0;
            this.m_dryingRestTime_Text.EnabledDynamicsValue = true;
            this.m_dryingRestTime_Text.FontSizePixels = 22;
            this.m_dryingRestTime_Text.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_dryingRestTime_Text.Height = 35;
            this.m_dryingRestTime_Text.Left = 10;
            this.m_dryingRestTime_Text.Name = "m_dryingRestTime_Text";
            this.m_dryingRestTime_Text.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5.5D, 0D, 5.5D, 1D);
            this.m_dryingRestTime_Text.ScreenOwnerName = "Admin_Page";
            this.m_dryingRestTime_Text.TextVerticalAlignment = "Center";
            this.m_dryingRestTime_Text.Top = 213;
            this.m_dryingRestTime_Text.VisibleDynamicsValue = true;
            this.m_dryingRestTime_Text.Width = 585;
            // 
            // m_cleaningWaterTime_Text
            // 
            this.m_cleaningWaterTime_Text.AutoSize = false;
            this.m_cleaningWaterTime_Text.BlinkDynamicsValue = false;
            this.m_cleaningWaterTime_Text.Bold = true;
            this.m_cleaningWaterTime_Text.DelayMouseInputPeriod = 0;
            this.m_cleaningWaterTime_Text.EnabledDynamicsValue = true;
            this.m_cleaningWaterTime_Text.FontSizePixels = 22;
            this.m_cleaningWaterTime_Text.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_cleaningWaterTime_Text.Height = 35;
            this.m_cleaningWaterTime_Text.Left = 10;
            this.m_cleaningWaterTime_Text.Name = "m_cleaningWaterTime_Text";
            this.m_cleaningWaterTime_Text.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5.5D, 0D, 5.5D, 1D);
            this.m_cleaningWaterTime_Text.ScreenOwnerName = "Admin_Page";
            this.m_cleaningWaterTime_Text.TextVerticalAlignment = "Center";
            this.m_cleaningWaterTime_Text.Top = 262;
            this.m_cleaningWaterTime_Text.VisibleDynamicsValue = true;
            this.m_cleaningWaterTime_Text.Width = 585;
            // 
            // m_cleaningPressTime_Text
            // 
            this.m_cleaningPressTime_Text.AutoSize = false;
            this.m_cleaningPressTime_Text.BlinkDynamicsValue = false;
            this.m_cleaningPressTime_Text.Bold = true;
            this.m_cleaningPressTime_Text.DelayMouseInputPeriod = 0;
            this.m_cleaningPressTime_Text.EnabledDynamicsValue = true;
            this.m_cleaningPressTime_Text.FontSizePixels = 22;
            this.m_cleaningPressTime_Text.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_cleaningPressTime_Text.Height = 35;
            this.m_cleaningPressTime_Text.Left = 10;
            this.m_cleaningPressTime_Text.Name = "m_cleaningPressTime_Text";
            this.m_cleaningPressTime_Text.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5.5D, 0D, 5.5D, 1D);
            this.m_cleaningPressTime_Text.ScreenOwnerName = "Admin_Page";
            this.m_cleaningPressTime_Text.TextVerticalAlignment = "Center";
            this.m_cleaningPressTime_Text.Top = 311;
            this.m_cleaningPressTime_Text.VisibleDynamicsValue = true;
            this.m_cleaningPressTime_Text.Width = 585;
            // 
            // m_prewashRestTime_Text
            // 
            this.m_prewashRestTime_Text.AutoSize = false;
            this.m_prewashRestTime_Text.BlinkDynamicsValue = false;
            this.m_prewashRestTime_Text.Bold = true;
            this.m_prewashRestTime_Text.DelayMouseInputPeriod = 0;
            this.m_prewashRestTime_Text.EnabledDynamicsValue = true;
            this.m_prewashRestTime_Text.FontSizePixels = 22;
            this.m_prewashRestTime_Text.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_prewashRestTime_Text.Height = 35;
            this.m_prewashRestTime_Text.Left = 10;
            this.m_prewashRestTime_Text.Name = "m_prewashRestTime_Text";
            this.m_prewashRestTime_Text.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5.5D, 0D, 5.5D, 1D);
            this.m_prewashRestTime_Text.ScreenOwnerName = "Admin_Page";
            this.m_prewashRestTime_Text.TextVerticalAlignment = "Center";
            this.m_prewashRestTime_Text.Top = 115;
            this.m_prewashRestTime_Text.VisibleDynamicsValue = true;
            this.m_prewashRestTime_Text.Width = 585;
            // 
            // m_prewashWaterTime_Num
            // 
            this.m_prewashWaterTime_Num.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_prewashWaterTime_Num.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_prewashWaterTime_Num.BlinkDynamicsValue = false;
            this.m_prewashWaterTime_Num.Bold = true;
            this.m_prewashWaterTime_Num.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_prewashWaterTime_Num.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_prewashWaterTime_Num.DelayMouseInputPeriod = 0;
            this.m_prewashWaterTime_Num.EnabledDynamicsValue = true;
            this.m_prewashWaterTime_Num.FontSizePixels = 20;
            this.m_prewashWaterTime_Num.Height = 35;
            this.m_prewashWaterTime_Num.Left = 606;
            this.m_prewashWaterTime_Num.MaxNumberOfCharacters = 3;
            this.m_prewashWaterTime_Num.MaxValue = 5000D;
            this.m_prewashWaterTime_Num.Name = "m_prewashWaterTime_Num";
            this.m_prewashWaterTime_Num.NumberOfDecimals = 0;
            this.m_prewashWaterTime_Num.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_prewashWaterTime_Num.ScreenOwnerName = "Admin_Page";
            this.m_prewashWaterTime_Num.Top = 66;
            this.m_prewashWaterTime_Num.ValidateValueOnInput = true;
            this.m_prewashWaterTime_Num.VisibleDynamicsValue = true;
            this.m_prewashWaterTime_Num.Width = 150;
            // 
            // m_prewashRestTime_Num
            // 
            this.m_prewashRestTime_Num.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_prewashRestTime_Num.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_prewashRestTime_Num.BlinkDynamicsValue = false;
            this.m_prewashRestTime_Num.Bold = true;
            this.m_prewashRestTime_Num.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_prewashRestTime_Num.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_prewashRestTime_Num.DelayMouseInputPeriod = 0;
            this.m_prewashRestTime_Num.EnabledDynamicsValue = true;
            this.m_prewashRestTime_Num.FontSizePixels = 20;
            this.m_prewashRestTime_Num.Height = 35;
            this.m_prewashRestTime_Num.Left = 606;
            this.m_prewashRestTime_Num.MaxNumberOfCharacters = 3;
            this.m_prewashRestTime_Num.MaxValue = 5000D;
            this.m_prewashRestTime_Num.Name = "m_prewashRestTime_Num";
            this.m_prewashRestTime_Num.NumberOfDecimals = 0;
            this.m_prewashRestTime_Num.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_prewashRestTime_Num.ScreenOwnerName = "Admin_Page";
            this.m_prewashRestTime_Num.Top = 115;
            this.m_prewashRestTime_Num.ValidateValueOnInput = true;
            this.m_prewashRestTime_Num.VisibleDynamicsValue = true;
            this.m_prewashRestTime_Num.Width = 150;
            // 
            // m_dryingAirTime_Num
            // 
            this.m_dryingAirTime_Num.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_dryingAirTime_Num.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_dryingAirTime_Num.BlinkDynamicsValue = false;
            this.m_dryingAirTime_Num.Bold = true;
            this.m_dryingAirTime_Num.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_dryingAirTime_Num.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_dryingAirTime_Num.DelayMouseInputPeriod = 0;
            this.m_dryingAirTime_Num.EnabledDynamicsValue = true;
            this.m_dryingAirTime_Num.FontSizePixels = 20;
            this.m_dryingAirTime_Num.Height = 35;
            this.m_dryingAirTime_Num.Left = 606;
            this.m_dryingAirTime_Num.MaxNumberOfCharacters = 3;
            this.m_dryingAirTime_Num.MaxValue = 5000D;
            this.m_dryingAirTime_Num.Name = "m_dryingAirTime_Num";
            this.m_dryingAirTime_Num.NumberOfDecimals = 0;
            this.m_dryingAirTime_Num.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_dryingAirTime_Num.ScreenOwnerName = "Admin_Page";
            this.m_dryingAirTime_Num.Top = 164;
            this.m_dryingAirTime_Num.ValidateValueOnInput = true;
            this.m_dryingAirTime_Num.VisibleDynamicsValue = true;
            this.m_dryingAirTime_Num.Width = 150;
            // 
            // m_dryingRestTime_Num
            // 
            this.m_dryingRestTime_Num.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_dryingRestTime_Num.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_dryingRestTime_Num.BlinkDynamicsValue = false;
            this.m_dryingRestTime_Num.Bold = true;
            this.m_dryingRestTime_Num.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_dryingRestTime_Num.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_dryingRestTime_Num.DelayMouseInputPeriod = 0;
            this.m_dryingRestTime_Num.EnabledDynamicsValue = true;
            this.m_dryingRestTime_Num.FontSizePixels = 20;
            this.m_dryingRestTime_Num.Height = 35;
            this.m_dryingRestTime_Num.Left = 606;
            this.m_dryingRestTime_Num.MaxNumberOfCharacters = 3;
            this.m_dryingRestTime_Num.MaxValue = 5000D;
            this.m_dryingRestTime_Num.Name = "m_dryingRestTime_Num";
            this.m_dryingRestTime_Num.NumberOfDecimals = 0;
            this.m_dryingRestTime_Num.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_dryingRestTime_Num.ScreenOwnerName = "Admin_Page";
            this.m_dryingRestTime_Num.Top = 213;
            this.m_dryingRestTime_Num.ValidateValueOnInput = true;
            this.m_dryingRestTime_Num.VisibleDynamicsValue = true;
            this.m_dryingRestTime_Num.Width = 150;
            // 
            // m_cleaningWaterTime_Num
            // 
            this.m_cleaningWaterTime_Num.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_cleaningWaterTime_Num.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_cleaningWaterTime_Num.BlinkDynamicsValue = false;
            this.m_cleaningWaterTime_Num.Bold = true;
            this.m_cleaningWaterTime_Num.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_cleaningWaterTime_Num.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_cleaningWaterTime_Num.DelayMouseInputPeriod = 0;
            this.m_cleaningWaterTime_Num.EnabledDynamicsValue = true;
            this.m_cleaningWaterTime_Num.FontSizePixels = 20;
            this.m_cleaningWaterTime_Num.Height = 35;
            this.m_cleaningWaterTime_Num.Left = 606;
            this.m_cleaningWaterTime_Num.MaxNumberOfCharacters = 3;
            this.m_cleaningWaterTime_Num.MaxValue = 5000D;
            this.m_cleaningWaterTime_Num.MinValue = 1D;
            this.m_cleaningWaterTime_Num.Name = "m_cleaningWaterTime_Num";
            this.m_cleaningWaterTime_Num.NumberOfDecimals = 0;
            this.m_cleaningWaterTime_Num.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_cleaningWaterTime_Num.ScreenOwnerName = "Admin_Page";
            this.m_cleaningWaterTime_Num.Top = 262;
            this.m_cleaningWaterTime_Num.ValidateValueOnInput = true;
            this.m_cleaningWaterTime_Num.VisibleDynamicsValue = true;
            this.m_cleaningWaterTime_Num.Width = 150;
            // 
            // m_cleaningPressTime_Num
            // 
            this.m_cleaningPressTime_Num.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_cleaningPressTime_Num.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_cleaningPressTime_Num.BlinkDynamicsValue = false;
            this.m_cleaningPressTime_Num.Bold = true;
            this.m_cleaningPressTime_Num.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_cleaningPressTime_Num.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_cleaningPressTime_Num.DelayMouseInputPeriod = 0;
            this.m_cleaningPressTime_Num.EnabledDynamicsValue = true;
            this.m_cleaningPressTime_Num.FontSizePixels = 20;
            this.m_cleaningPressTime_Num.Height = 35;
            this.m_cleaningPressTime_Num.Left = 606;
            this.m_cleaningPressTime_Num.MaxNumberOfCharacters = 3;
            this.m_cleaningPressTime_Num.MaxValue = 5000D;
            this.m_cleaningPressTime_Num.MinValue = 1D;
            this.m_cleaningPressTime_Num.Name = "m_cleaningPressTime_Num";
            this.m_cleaningPressTime_Num.NumberOfDecimals = 0;
            this.m_cleaningPressTime_Num.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_cleaningPressTime_Num.ScreenOwnerName = "Admin_Page";
            this.m_cleaningPressTime_Num.Top = 311;
            this.m_cleaningPressTime_Num.ValidateValueOnInput = true;
            this.m_cleaningPressTime_Num.VisibleDynamicsValue = true;
            this.m_cleaningPressTime_Num.Width = 150;
            // 
            // m_cleaningRestTime_Num
            // 
            this.m_cleaningRestTime_Num.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_cleaningRestTime_Num.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_cleaningRestTime_Num.BlinkDynamicsValue = false;
            this.m_cleaningRestTime_Num.Bold = true;
            this.m_cleaningRestTime_Num.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_cleaningRestTime_Num.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_cleaningRestTime_Num.DelayMouseInputPeriod = 0;
            this.m_cleaningRestTime_Num.EnabledDynamicsValue = true;
            this.m_cleaningRestTime_Num.FontSizePixels = 20;
            this.m_cleaningRestTime_Num.Height = 35;
            this.m_cleaningRestTime_Num.Left = 606;
            this.m_cleaningRestTime_Num.MaxNumberOfCharacters = 3;
            this.m_cleaningRestTime_Num.MaxValue = 5000D;
            this.m_cleaningRestTime_Num.MinValue = 1D;
            this.m_cleaningRestTime_Num.Name = "m_cleaningRestTime_Num";
            this.m_cleaningRestTime_Num.NumberOfDecimals = 0;
            this.m_cleaningRestTime_Num.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_cleaningRestTime_Num.ScreenOwnerName = "Admin_Page";
            this.m_cleaningRestTime_Num.Top = 360;
            this.m_cleaningRestTime_Num.ValidateValueOnInput = true;
            this.m_cleaningRestTime_Num.VisibleDynamicsValue = true;
            this.m_cleaningRestTime_Num.Width = 150;
            // 
            // m_Warning_Text
            // 
            this.m_Warning_Text.AutoSize = false;
            this.m_Warning_Text.BlinkDynamicsValue = false;
            this.m_Warning_Text.Bold = true;
            this.m_Warning_Text.DelayMouseInputPeriod = 0;
            this.m_Warning_Text.EnabledDynamicsValue = true;
            this.m_Warning_Text.FontSizePixels = 20;
            this.m_Warning_Text.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.m_Warning_Text.Height = 50;
            this.m_Warning_Text.Left = -1;
            this.m_Warning_Text.Name = "m_Warning_Text";
            this.m_Warning_Text.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 0D, 5D, 1D);
            this.m_Warning_Text.ScreenOwnerName = "Admin_Page";
            this.m_Warning_Text.TextHorizontalAlignment = "Center";
            this.m_Warning_Text.TextVerticalAlignment = "Center";
            this.m_Warning_Text.Top = 440;
            this.m_Warning_Text.Underline = true;
            this.m_Warning_Text.VisibleDynamicsValue = true;
            this.m_Warning_Text.Width = 800;
            // 
            // m_testTime_Num
            // 
            this.m_testTime_Num.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_testTime_Num.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_testTime_Num.BlinkDynamicsValue = false;
            this.m_testTime_Num.Bold = true;
            this.m_testTime_Num.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_testTime_Num.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_testTime_Num.DelayMouseInputPeriod = 0;
            this.m_testTime_Num.EnabledDynamicsValue = true;
            this.m_testTime_Num.FontSizePixels = 20;
            this.m_testTime_Num.Height = 35;
            this.m_testTime_Num.Left = 606;
            this.m_testTime_Num.MaxNumberOfCharacters = 3;
            this.m_testTime_Num.MaxValue = 5000D;
            this.m_testTime_Num.MinValue = 1D;
            this.m_testTime_Num.Name = "m_testTime_Num";
            this.m_testTime_Num.NumberOfDecimals = 0;
            this.m_testTime_Num.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_testTime_Num.ScreenOwnerName = "Admin_Page";
            this.m_testTime_Num.Top = 17;
            this.m_testTime_Num.ValidateValueOnInput = true;
            this.m_testTime_Num.VisibleDynamicsValue = true;
            this.m_testTime_Num.Width = 150;
            // 
            // m_TestTime_Text
            // 
            this.m_TestTime_Text.AutoSize = false;
            this.m_TestTime_Text.BlinkDynamicsValue = false;
            this.m_TestTime_Text.Bold = true;
            this.m_TestTime_Text.DelayMouseInputPeriod = 0;
            this.m_TestTime_Text.EnabledDynamicsValue = true;
            this.m_TestTime_Text.FontSizePixels = 22;
            this.m_TestTime_Text.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_TestTime_Text.Height = 35;
            this.m_TestTime_Text.Left = 120;
            this.m_TestTime_Text.Name = "m_TestTime_Text";
            this.m_TestTime_Text.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5.5D, 0D, 5.5D, 1D);
            this.m_TestTime_Text.ScreenOwnerName = "Admin_Page";
            this.m_TestTime_Text.TextVerticalAlignment = "Center";
            this.m_TestTime_Text.Top = 17;
            this.m_TestTime_Text.VisibleDynamicsValue = true;
            this.m_TestTime_Text.Width = 475;
            // 
            // m_Text
            // 
            this.m_Text.AutoSize = false;
            this.m_Text.BlinkDynamicsValue = false;
            this.m_Text.Bold = true;
            this.m_Text.DelayMouseInputPeriod = 0;
            this.m_Text.EnabledDynamicsValue = true;
            this.m_Text.FontSizePixels = 22;
            this.m_Text.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Text.Height = 35;
            this.m_Text.Left = 10;
            this.m_Text.Name = "m_Text";
            this.m_Text.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5.5D, 0D, 5.5D, 1D);
            this.m_Text.ScreenOwnerName = "Admin_Page";
            this.m_Text.TextVerticalAlignment = "Center";
            this.m_Text.Top = 410;
            this.m_Text.VisibleDynamicsValue = true;
            this.m_Text.Width = 585;
            // 
            // m_AnalogNumeric
            // 
            this.m_AnalogNumeric.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_AnalogNumeric.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_AnalogNumeric.BlinkDynamicsValue = false;
            this.m_AnalogNumeric.Bold = true;
            this.m_AnalogNumeric.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_AnalogNumeric.DelayMouseInputPeriod = 0;
            this.m_AnalogNumeric.EnabledDynamicsValue = true;
            this.m_AnalogNumeric.FontSizePixels = 20;
            this.m_AnalogNumeric.Height = 35;
            this.m_AnalogNumeric.Left = 606;
            this.m_AnalogNumeric.MaxNumberOfCharacters = 2;
            this.m_AnalogNumeric.MaxValue = 30D;
            this.m_AnalogNumeric.MinValue = 1D;
            this.m_AnalogNumeric.Name = "m_AnalogNumeric";
            this.m_AnalogNumeric.NumberOfDecimals = 0;
            this.m_AnalogNumeric.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_AnalogNumeric.ScreenOwnerName = "Admin_Page";
            this.m_AnalogNumeric.Top = 410;
            this.m_AnalogNumeric.ValidateValueOnInput = true;
            this.m_AnalogNumeric.VisibleDynamicsValue = true;
            this.m_AnalogNumeric.Width = 150;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "Admin_Page";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_Admin_Page = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_Admin_Page) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_Logo);
            this.DrawingPrimitives.Add(this.m_Back_Button);
            this.DrawingPrimitives.Add(this.m_prewashWaterTime_Text);
            this.DrawingPrimitives.Add(this.m_cleaningRestTime_Text);
            this.DrawingPrimitives.Add(this.m_dryingAirTime_Text);
            this.DrawingPrimitives.Add(this.m_dryingRestTime_Text);
            this.DrawingPrimitives.Add(this.m_cleaningWaterTime_Text);
            this.DrawingPrimitives.Add(this.m_cleaningPressTime_Text);
            this.DrawingPrimitives.Add(this.m_prewashRestTime_Text);
            this.DrawingPrimitives.Add(this.m_prewashWaterTime_Num);
            this.DrawingPrimitives.Add(this.m_prewashRestTime_Num);
            this.DrawingPrimitives.Add(this.m_dryingAirTime_Num);
            this.DrawingPrimitives.Add(this.m_dryingRestTime_Num);
            this.DrawingPrimitives.Add(this.m_cleaningWaterTime_Num);
            this.DrawingPrimitives.Add(this.m_cleaningPressTime_Num);
            this.DrawingPrimitives.Add(this.m_cleaningRestTime_Num);
            this.DrawingPrimitives.Add(this.m_Warning_Text);
            this.DrawingPrimitives.Add(this.m_testTime_Num);
            this.DrawingPrimitives.Add(this.m_TestTime_Text);
            this.DrawingPrimitives.Add(this.m_Text);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric);
            ((System.ComponentModel.ISupportInitialize)(this.m_Logo)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Back_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_prewashWaterTime_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_cleaningRestTime_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_dryingAirTime_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_dryingRestTime_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_cleaningWaterTime_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_cleaningPressTime_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_prewashRestTime_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_prewashWaterTime_Num)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_prewashRestTime_Num)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_dryingAirTime_Num)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_dryingRestTime_Num)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_cleaningWaterTime_Num)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_cleaningPressTime_Num)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_cleaningRestTime_Num)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Warning_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_testTime_Num)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_TestTime_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric)).EndInit();
        }
        
        private void m_Back_Button_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Back_Button", "Click", "Show Screen", "Settings_Screen", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.Settings_Screen.Show();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Admin_Page));
            this.m_Back_Button.Text = resources.GetText("Admin_Page.Back_Button.Text", "BACK");
            this.m_prewashWaterTime_Text.Text = resources.GetText("Admin_Page.prewashWaterTime_Text.Text", "Pre-Wash Water Timer");
            this.m_cleaningRestTime_Text.Text = resources.GetText("Admin_Page.cleaningRestTime_Text.Text", "Cleaning Resting Timer");
            this.m_dryingAirTime_Text.Text = resources.GetText("Admin_Page.dryingAirTime_Text.Text", "Drying Air Timer");
            this.m_dryingRestTime_Text.Text = resources.GetText("Admin_Page.dryingRestTime_Text.Text", "Drying Resting Timer");
            this.m_cleaningWaterTime_Text.Text = resources.GetText("Admin_Page.cleaningWaterTime_Text.Text", "Cleaning Washing Timer");
            this.m_cleaningPressTime_Text.Text = resources.GetText("Admin_Page.cleaningPressTime_Text.Text", "Cleaning Pressure Washing Timer");
            this.m_prewashRestTime_Text.Text = resources.GetText("Admin_Page.prewashRestTime_Text.Text", "Pre-Wash Resting Timer");
            this.m_prewashWaterTime_Num.Suffix = resources.GetText("Admin_Page.prewashWaterTime_Num.Suffix", " sec");
            this.m_prewashRestTime_Num.Suffix = resources.GetText("Admin_Page.prewashRestTime_Num.Suffix", " sec");
            this.m_dryingAirTime_Num.Suffix = resources.GetText("Admin_Page.dryingAirTime_Num.Suffix", " sec");
            this.m_dryingRestTime_Num.Suffix = resources.GetText("Admin_Page.dryingRestTime_Num.Suffix", " sec");
            this.m_cleaningWaterTime_Num.Suffix = resources.GetText("Admin_Page.cleaningWaterTime_Num.Suffix", " sec");
            this.m_cleaningPressTime_Num.Suffix = resources.GetText("Admin_Page.cleaningPressTime_Num.Suffix", " sec");
            this.m_cleaningRestTime_Num.Suffix = resources.GetText("Admin_Page.cleaningRestTime_Num.Suffix", " sec");
            this.m_Warning_Text.Text = resources.GetText("Admin_Page.Warning_Text.Text", "You Accept the Risk by Changing the Values");
            this.m_testTime_Num.Suffix = resources.GetText("Admin_Page.testTime_Num.Suffix", " sec.");
            this.m_TestTime_Text.Text = resources.GetText("Admin_Page.TestTime_Text.Text", "Filter Testing Time");
            this.m_Text.Text = resources.GetText("Admin_Page.Text.Text", "Filter Changing Counter Limit");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage() {
            this.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_Admin_Page) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.prewashWaterTime"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_prewashWaterTime_Num.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.prewashRestTime"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_prewashRestTime_Num.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding3 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.dryingAirTime"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_dryingAirTime_Num.DataBindings.Add(dynamicBinding3);
            this.m_DynamicBindings.Add(dynamicBinding3);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding4 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.dryingRestTime"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_dryingRestTime_Num.DataBindings.Add(dynamicBinding4);
            this.m_DynamicBindings.Add(dynamicBinding4);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding5 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.cleaningWaterTime"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_cleaningWaterTime_Num.DataBindings.Add(dynamicBinding5);
            this.m_DynamicBindings.Add(dynamicBinding5);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding6 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.cleaningPressTime"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_cleaningPressTime_Num.DataBindings.Add(dynamicBinding6);
            this.m_DynamicBindings.Add(dynamicBinding6);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding7 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.cleaningRestTime"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_cleaningRestTime_Num.DataBindings.Add(dynamicBinding7);
            this.m_DynamicBindings.Add(dynamicBinding7);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding8 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.TestTime"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_testTime_Num.DataBindings.Add(dynamicBinding8);
            this.m_DynamicBindings.Add(dynamicBinding8);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding9 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.CleaningCounterLimit"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric.DataBindings.Add(dynamicBinding9);
            this.m_DynamicBindings.Add(dynamicBinding9);
        }
    }
}
