//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class Drying_Screen : Neo.ApplicationFramework.Controls.Controls.Form, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage {
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Logo;
        
        private Neo.ApplicationFramework.Controls.Controls.EllipseCF m_Drying_Status;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Drying_Start;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Drying_Time_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_Drying_Min_Set;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Stable_Down;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button4;
        
        private Neo.ApplicationFramework.Controls.Controls.GroupCF m_Filter_Stabilizer_Control;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Door_Open_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Door_Close_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.GroupCF m_Door_Control;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Test_Nav;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Home_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Auto_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Manuel_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Alarm_button;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Drying_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.DigitalClockCF m_DigitalClock3;
        
        private Neo.ApplicationFramework.Controls.Controls.DigitalClockCF m_DigitalClock4;
        
        private Neo.ApplicationFramework.Controls.Controls.GroupCF m_DateClock;
        
        private Neo.ApplicationFramework.Controls.Controls.GroupCF m_Navigation;
        
        private Neo.ApplicationFramework.Controls.Symbol.SymbolCF m_Lamp_Switch;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text4;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text2;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Drying_Heat_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_Drying_Heat_Set;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Current_Heat_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_Current_Heat;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text1;
        
        private bool m_Initialized_Drying_Screen;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf1;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf2;
        
        public Drying_Screen() {
            this.InitializeComponent();
            this.Drying_Start.Click += new System.EventHandler(this.Drying_Start_Click);
            this.Adapter.Opened += new System.EventHandler(this.Drying_Screen_Opened);
            this.m_Stable_Down.MouseDown += new System.EventHandler(this.m_Stable_Down_Action_PreviewMouseDown);
            this.m_Stable_Down.MouseUp += new System.EventHandler(this.m_Stable_Down_Action_PreviewMouseUp);
            this.m_Button4.MouseDown += new System.EventHandler(this.m_Button4_Action_PreviewMouseDown);
            this.m_Button4.MouseUp += new System.EventHandler(this.m_Button4_Action_PreviewMouseUp);
            this.m_Door_Open_Button.MouseDown += new System.EventHandler(this.m_Door_Open_Button_Action_PreviewMouseDown);
            this.m_Door_Open_Button.MouseUp += new System.EventHandler(this.m_Door_Open_Button_Action_PreviewMouseUp);
            this.m_Door_Close_Button.MouseDown += new System.EventHandler(this.m_Door_Close_Button_Action_PreviewMouseDown);
            this.m_Door_Close_Button.MouseUp += new System.EventHandler(this.m_Door_Close_Button_Action_PreviewMouseUp);
            this.m_Test_Nav.Click += new System.EventHandler(this.m_Test_Nav_Action_Click);
            this.m_Home_Button.Click += new System.EventHandler(this.m_Home_Button_Action_Click);
            this.m_Auto_Button.Click += new System.EventHandler(this.m_Auto_Button_Action_Click);
            this.m_Manuel_Button.Click += new System.EventHandler(this.m_Manuel_Button_Action_Click);
            this.m_Alarm_button.Click += new System.EventHandler(this.m_Alarm_button_Action_Click);
            this.m_Lamp_Switch.MouseDown += new System.EventHandler(this.m_Lamp_Switch_Action_MouseDown);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Logo {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Logo);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Drying_Status {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Drying_Status);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Drying_Start {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Drying_Start);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Drying_Time_Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Drying_Time_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter Drying_Min_Set {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_Drying_Min_Set);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.GroupCFAdapter Filter_Stabilizer_Control {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.GroupCFAdapter>(this.m_Filter_Stabilizer_Control);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Stable_Down {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Stable_Down);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.GroupCFAdapter Door_Control {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.GroupCFAdapter>(this.m_Door_Control);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Door_Open_Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Door_Open_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Door_Close_Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Door_Close_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.GroupCFAdapter Navigation {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.GroupCFAdapter>(this.m_Navigation);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Test_Nav {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Test_Nav);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Home_Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Home_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Auto_Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Auto_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Manuel_Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Manuel_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Alarm_button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Alarm_button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Drying_Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Drying_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.GroupCFAdapter DateClock {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.GroupCFAdapter>(this.m_DateClock);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter DigitalClock3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_DigitalClock3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter DigitalClock4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_DigitalClock4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Lamp_Switch {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Lamp_Switch);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Drying_Heat_Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Drying_Heat_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter Drying_Heat_Set {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_Drying_Heat_Set);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Current_Heat_Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Current_Heat_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter Current_Heat {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_Current_Heat);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text1);
            }
        }
        
        private void InitializeComponent() {
            this.brushdynamicsconvertercf2 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            this.brushdynamicsconvertercf1 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval1 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval2 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval3 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval4 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper5 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper6 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper7 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper8 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper9 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper10 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper11 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper12 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem1 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem2 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            this.m_Logo = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Drying_Status = new Neo.ApplicationFramework.Controls.Controls.EllipseCF();
            this.m_Drying_Start = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Drying_Time_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Drying_Min_Set = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_Stable_Down = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button4 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Filter_Stabilizer_Control = new Neo.ApplicationFramework.Controls.Controls.GroupCF();
            this.m_Door_Open_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Door_Close_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Door_Control = new Neo.ApplicationFramework.Controls.Controls.GroupCF();
            this.m_Test_Nav = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Home_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Auto_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Manuel_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Alarm_button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Rectangle = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Drying_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_DigitalClock3 = new Neo.ApplicationFramework.Controls.Controls.DigitalClockCF();
            this.m_DigitalClock4 = new Neo.ApplicationFramework.Controls.Controls.DigitalClockCF();
            this.m_DateClock = new Neo.ApplicationFramework.Controls.Controls.GroupCF();
            this.m_Navigation = new Neo.ApplicationFramework.Controls.Controls.GroupCF();
            this.m_Lamp_Switch = new Neo.ApplicationFramework.Controls.Symbol.SymbolCF();
            this.m_Text4 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text2 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Drying_Heat_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Drying_Heat_Set = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_Current_Heat_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Current_Heat = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text1 = new Neo.ApplicationFramework.Controls.Controls.Label();
            ((System.ComponentModel.ISupportInitialize)(this.m_Logo)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Drying_Start)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Drying_Time_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Drying_Min_Set)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Stable_Down)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Filter_Stabilizer_Control)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Door_Open_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Door_Close_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Door_Control)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Test_Nav)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Home_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Auto_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Manuel_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Alarm_button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Drying_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_DigitalClock3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_DigitalClock4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_DateClock)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Navigation)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Lamp_Switch)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Drying_Heat_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Drying_Heat_Set)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Current_Heat_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Current_Heat)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).BeginInit();
            this.SuspendLayout();
            // 
            // Drying_Screen
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(130)))), ((int)(((byte)(31))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.ThreeDBorder;
            this.ControlBox = false;
            // 
            // m_Logo
            // 
            this.m_Logo.BlinkDynamicsValue = false;
            this.m_Logo.DelayMouseInputPeriod = 0;
            this.m_Logo.EnabledDynamicsValue = true;
            this.m_Logo.Height = 482;
            this.m_Logo.Left = 464;
            this.m_Logo.Name = "m_Logo";
            this.m_Logo.ScreenOwnerName = "Drying_Screen";
            this.m_Logo.Stretch = true;
            this.m_Logo.SymbolName = "logobeyaz";
            this.m_Logo.Top = 17;
            this.m_Logo.VisibleDynamicsValue = true;
            this.m_Logo.Width = 475;
            // 
            // m_Drying_Status
            // 
            this.m_Drying_Status.BlinkDynamicsValue = false;
            brushdynamicsconvertercf1.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.SteelBlue, System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval1.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.White, System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval2.End = 1D;
            brushcfinterval2.Start = 1D;
            brushcfinterval2.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(177)))), ((int)(((byte)(76))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushdynamicsconvertercf1.BrushIntervalMapper.Intervals.Add(brushcfinterval1);
            brushdynamicsconvertercf1.BrushIntervalMapper.Intervals.Add(brushcfinterval2);
            this.m_Drying_Status.DelayMouseInputPeriod = 0;
            this.m_Drying_Status.EnabledDynamicsValue = true;
            this.m_Drying_Status.Fill = null;
            this.m_Drying_Status.Height = 58;
            this.m_Drying_Status.Left = 186;
            this.m_Drying_Status.Name = "m_Drying_Status";
            this.m_Drying_Status.ScreenOwnerName = "Drying_Screen";
            this.m_Drying_Status.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Drying_Status.StrokeThickness = 2;
            this.m_Drying_Status.Top = 106;
            this.m_Drying_Status.VisibleDynamicsValue = true;
            this.m_Drying_Status.Width = 58;
            // 
            // m_Drying_Start
            // 
            this.m_Drying_Start.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(49)))), ((int)(((byte)(146))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Drying_Start.BlinkDynamicsValue = false;
            this.m_Drying_Start.Bold = true;
            this.m_Drying_Start.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Drying_Start.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 5D, 5D, 5D);
            brushdynamicsconvertercf2.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.White, System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval3.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.White, System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval4.End = 1D;
            brushcfinterval4.Start = 1D;
            brushcfinterval4.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(177)))), ((int)(((byte)(76))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushdynamicsconvertercf2.BrushIntervalMapper.Intervals.Add(brushcfinterval3);
            brushdynamicsconvertercf2.BrushIntervalMapper.Intervals.Add(brushcfinterval4);
            this.m_Drying_Start.DelayMouseInputPeriod = 0;
            this.m_Drying_Start.EnabledDynamicsValue = true;
            this.m_Drying_Start.FontSizePixels = 28;
            this.m_Drying_Start.ForceTransparency = true;
            this.m_Drying_Start.Height = 93;
            this.m_Drying_Start.IndicatorMargin = null;
            this.m_Drying_Start.Left = 19;
            this.m_Drying_Start.Name = "m_Drying_Start";
            this.m_Drying_Start.RequiresTransparency = true;
            this.m_Drying_Start.ScreenOwnerName = "Drying_Screen";
            this.m_Drying_Start.StyleName = "Chrome";
            this.m_Drying_Start.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_Drying_Start.TextHeight = 34;
            this.m_Drying_Start.TextValue = 0D;
            this.m_Drying_Start.TextWidth = 150;
            this.m_Drying_Start.Top = 89;
            this.m_Drying_Start.Value = 0D;
            this.m_Drying_Start.VisibleDynamicsValue = true;
            this.m_Drying_Start.VisualPropertiesHashCode = -1729577388;
            this.m_Drying_Start.Width = 156;
            // 
            // m_Drying_Time_Text
            // 
            this.m_Drying_Time_Text.AutoSize = false;
            this.m_Drying_Time_Text.BlinkDynamicsValue = false;
            this.m_Drying_Time_Text.Bold = true;
            this.m_Drying_Time_Text.DelayMouseInputPeriod = 0;
            this.m_Drying_Time_Text.EnabledDynamicsValue = true;
            this.m_Drying_Time_Text.FontSizePixels = 18;
            this.m_Drying_Time_Text.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Drying_Time_Text.Height = 39;
            this.m_Drying_Time_Text.Left = 19;
            this.m_Drying_Time_Text.Name = "m_Drying_Time_Text";
            this.m_Drying_Time_Text.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(4.5D, 0D, 4.5D, 1D);
            this.m_Drying_Time_Text.ScreenOwnerName = "Drying_Screen";
            this.m_Drying_Time_Text.TextVerticalAlignment = "Center";
            this.m_Drying_Time_Text.Top = 182;
            this.m_Drying_Time_Text.VisibleDynamicsValue = true;
            this.m_Drying_Time_Text.Width = 281;
            // 
            // m_Drying_Min_Set
            // 
            this.m_Drying_Min_Set.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_Drying_Min_Set.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_Drying_Min_Set.BlinkDynamicsValue = false;
            this.m_Drying_Min_Set.Bold = true;
            this.m_Drying_Min_Set.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Drying_Min_Set.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Drying_Min_Set.DelayMouseInputPeriod = 0;
            this.m_Drying_Min_Set.EnabledDynamicsValue = true;
            this.m_Drying_Min_Set.FontSizePixels = 18;
            this.m_Drying_Min_Set.Height = 39;
            this.m_Drying_Min_Set.Left = 316;
            this.m_Drying_Min_Set.LimitNumberOfCharacters = true;
            this.m_Drying_Min_Set.MaxNumberOfCharacters = 3;
            this.m_Drying_Min_Set.MaxValue = 250D;
            this.m_Drying_Min_Set.MinValue = 1D;
            this.m_Drying_Min_Set.Name = "m_Drying_Min_Set";
            this.m_Drying_Min_Set.NumberOfDecimals = 0;
            this.m_Drying_Min_Set.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Drying_Min_Set.ScreenOwnerName = "Drying_Screen";
            this.m_Drying_Min_Set.Top = 182;
            this.m_Drying_Min_Set.ValidateValueOnInput = true;
            this.m_Drying_Min_Set.VisibleDynamicsValue = true;
            this.m_Drying_Min_Set.Width = 164;
            // 
            // m_Stable_Down
            // 
            this.m_Stable_Down.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Stable_Down.BlinkDynamicsValue = false;
            this.m_Stable_Down.Bold = true;
            this.m_Stable_Down.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Stable_Down.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 5D, 5D, 5D);
            this.m_Stable_Down.DelayMouseInputPeriod = 0;
            this.m_Stable_Down.EnabledDynamicsValue = true;
            this.m_Stable_Down.FontSizePixels = 14;
            this.m_Stable_Down.ForceTransparency = true;
            this.m_Stable_Down.Height = 58;
            this.m_Stable_Down.IndicatorMargin = null;
            this.m_Stable_Down.Left = 0;
            this.m_Stable_Down.MultiLine = true;
            this.m_Stable_Down.Name = "m_Stable_Down";
            this.m_Stable_Down.RequiresTransparency = true;
            this.m_Stable_Down.ScreenOwnerName = "Drying_Screen";
            this.m_Stable_Down.StyleName = "Chrome";
            this.m_Stable_Down.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_Stable_Down.TextHeight = 34;
            this.m_Stable_Down.TextValue = 0D;
            this.m_Stable_Down.TextWidth = 189;
            this.m_Stable_Down.Top = 71;
            this.m_Stable_Down.Value = 0D;
            this.m_Stable_Down.VisibleDynamicsValue = true;
            this.m_Stable_Down.VisualPropertiesHashCode = 420018005;
            this.m_Stable_Down.Width = 195;
            this.m_Stable_Down.WordWrap = true;
            // 
            // m_Button4
            // 
            this.m_Button4.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button4.BlinkDynamicsValue = false;
            this.m_Button4.Bold = true;
            this.m_Button4.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button4.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 5D, 5D, 5D);
            this.m_Button4.DelayMouseInputPeriod = 0;
            this.m_Button4.EnabledDynamicsValue = true;
            this.m_Button4.FontSizePixels = 14;
            this.m_Button4.ForceTransparency = true;
            this.m_Button4.Height = 58;
            this.m_Button4.IndicatorMargin = null;
            this.m_Button4.Left = 0;
            this.m_Button4.MultiLine = true;
            this.m_Button4.Name = "m_Button4";
            this.m_Button4.RequiresTransparency = true;
            this.m_Button4.ScreenOwnerName = "Drying_Screen";
            this.m_Button4.StyleName = "Chrome";
            this.m_Button4.SymbolIntervalMapper = symbolintervalmapper3;
            this.m_Button4.TextHeight = 34;
            this.m_Button4.TextValue = 0D;
            this.m_Button4.TextWidth = 189;
            this.m_Button4.Top = 0;
            this.m_Button4.Value = 0D;
            this.m_Button4.VisibleDynamicsValue = true;
            this.m_Button4.VisualPropertiesHashCode = 983584347;
            this.m_Button4.Width = 195;
            this.m_Button4.WordWrap = true;
            // 
            // m_Filter_Stabilizer_Control
            // 
            this.m_Filter_Stabilizer_Control.BlinkDynamicsValue = false;
            this.m_Filter_Stabilizer_Control.Components.Add(this.m_Stable_Down);
            this.m_Filter_Stabilizer_Control.Components.Add(this.m_Button4);
            this.m_Filter_Stabilizer_Control.DelayMouseInputPeriod = 0;
            this.m_Filter_Stabilizer_Control.EnabledDynamicsValue = true;
            this.m_Filter_Stabilizer_Control.Height = 130;
            this.m_Filter_Stabilizer_Control.Left = 240;
            this.m_Filter_Stabilizer_Control.Name = "m_Filter_Stabilizer_Control";
            this.m_Filter_Stabilizer_Control.ParentGroup = null;
            this.m_Filter_Stabilizer_Control.ScreenOwnerName = "Drying_Screen";
            this.m_Filter_Stabilizer_Control.Top = 316;
            this.m_Filter_Stabilizer_Control.VisibleDynamicsValue = true;
            this.m_Filter_Stabilizer_Control.Width = 195;
            // 
            // m_Door_Open_Button
            // 
            this.m_Door_Open_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Door_Open_Button.BlinkDynamicsValue = false;
            this.m_Door_Open_Button.Bold = true;
            this.m_Door_Open_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Door_Open_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 5D, 5D, 5D);
            this.m_Door_Open_Button.DelayMouseInputPeriod = 0;
            this.m_Door_Open_Button.EnabledDynamicsValue = true;
            this.m_Door_Open_Button.FontSizePixels = 14;
            this.m_Door_Open_Button.ForceTransparency = true;
            this.m_Door_Open_Button.Height = 58;
            this.m_Door_Open_Button.IndicatorMargin = null;
            this.m_Door_Open_Button.Left = 0;
            this.m_Door_Open_Button.MultiLine = true;
            this.m_Door_Open_Button.Name = "m_Door_Open_Button";
            this.m_Door_Open_Button.RequiresTransparency = true;
            this.m_Door_Open_Button.ScreenOwnerName = "Drying_Screen";
            this.m_Door_Open_Button.StyleName = "Chrome";
            this.m_Door_Open_Button.SymbolIntervalMapper = symbolintervalmapper4;
            this.m_Door_Open_Button.TextValue = 0D;
            this.m_Door_Open_Button.TextWidth = 189;
            this.m_Door_Open_Button.Top = 0;
            this.m_Door_Open_Button.Value = 0D;
            this.m_Door_Open_Button.VisibleDynamicsValue = true;
            this.m_Door_Open_Button.VisualPropertiesHashCode = 983584347;
            this.m_Door_Open_Button.Width = 195;
            this.m_Door_Open_Button.WordWrap = true;
            // 
            // m_Door_Close_Button
            // 
            this.m_Door_Close_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Door_Close_Button.BlinkDynamicsValue = false;
            this.m_Door_Close_Button.Bold = true;
            this.m_Door_Close_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Door_Close_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 5D, 5D, 5D);
            this.m_Door_Close_Button.DelayMouseInputPeriod = 0;
            this.m_Door_Close_Button.EnabledDynamicsValue = true;
            this.m_Door_Close_Button.FontSizePixels = 14;
            this.m_Door_Close_Button.ForceTransparency = true;
            this.m_Door_Close_Button.Height = 58;
            this.m_Door_Close_Button.IndicatorMargin = null;
            this.m_Door_Close_Button.Left = 0;
            this.m_Door_Close_Button.MultiLine = true;
            this.m_Door_Close_Button.Name = "m_Door_Close_Button";
            this.m_Door_Close_Button.RequiresTransparency = true;
            this.m_Door_Close_Button.ScreenOwnerName = "Drying_Screen";
            this.m_Door_Close_Button.StyleName = "Chrome";
            this.m_Door_Close_Button.SymbolIntervalMapper = symbolintervalmapper5;
            this.m_Door_Close_Button.TextValue = 0D;
            this.m_Door_Close_Button.TextWidth = 189;
            this.m_Door_Close_Button.Top = 71;
            this.m_Door_Close_Button.Value = 0D;
            this.m_Door_Close_Button.VisibleDynamicsValue = true;
            this.m_Door_Close_Button.VisualPropertiesHashCode = 420018005;
            this.m_Door_Close_Button.Width = 195;
            this.m_Door_Close_Button.WordWrap = true;
            // 
            // m_Door_Control
            // 
            this.m_Door_Control.BlinkDynamicsValue = false;
            this.m_Door_Control.Components.Add(this.m_Door_Open_Button);
            this.m_Door_Control.Components.Add(this.m_Door_Close_Button);
            this.m_Door_Control.DelayMouseInputPeriod = 0;
            this.m_Door_Control.EnabledDynamicsValue = true;
            this.m_Door_Control.Height = 130;
            this.m_Door_Control.Left = 19;
            this.m_Door_Control.Name = "m_Door_Control";
            this.m_Door_Control.ParentGroup = null;
            this.m_Door_Control.ScreenOwnerName = "Drying_Screen";
            this.m_Door_Control.Top = 316;
            this.m_Door_Control.VisibleDynamicsValue = true;
            this.m_Door_Control.Width = 195;
            // 
            // m_Test_Nav
            // 
            this.m_Test_Nav.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(49)))), ((int)(((byte)(146))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Test_Nav.BlinkDynamicsValue = false;
            this.m_Test_Nav.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Test_Nav.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 5D, 5D, 0D);
            this.m_Test_Nav.DelayMouseInputPeriod = 0;
            this.m_Test_Nav.EnabledDynamicsValue = true;
            this.m_Test_Nav.FontSizePixels = 16;
            this.m_Test_Nav.ForceTransparency = true;
            this.m_Test_Nav.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Test_Nav.Height = 58;
            this.m_Test_Nav.IndicatorMargin = null;
            this.m_Test_Nav.Left = 313;
            this.m_Test_Nav.MultiLine = true;
            this.m_Test_Nav.Name = "m_Test_Nav";
            this.m_Test_Nav.RequiresTransparency = true;
            this.m_Test_Nav.ScreenOwnerName = "Drying_Screen";
            this.m_Test_Nav.StyleName = "Vintage";
            this.m_Test_Nav.SymbolIntervalMapper = symbolintervalmapper6;
            this.m_Test_Nav.TextHeight = 19;
            this.m_Test_Nav.TextValue = 0D;
            this.m_Test_Nav.TextWidth = 91;
            this.m_Test_Nav.Top = 0;
            this.m_Test_Nav.Value = 0D;
            this.m_Test_Nav.VisibleDynamicsValue = true;
            this.m_Test_Nav.VisualPropertiesHashCode = -475964534;
            this.m_Test_Nav.Width = 97;
            // 
            // m_Home_Button
            // 
            this.m_Home_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(49)))), ((int)(((byte)(146))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Home_Button.BlinkDynamicsValue = false;
            this.m_Home_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Home_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 5D, 5D, 0D);
            this.m_Home_Button.DelayMouseInputPeriod = 0;
            this.m_Home_Button.EnabledDynamicsValue = true;
            this.m_Home_Button.FontSizePixels = 18;
            this.m_Home_Button.ForceTransparency = true;
            this.m_Home_Button.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Home_Button.Height = 58;
            this.m_Home_Button.ImageMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(10D, 10D, 10D, 10D);
            this.m_Home_Button.IndicatorMargin = null;
            this.m_Home_Button.Left = 1;
            this.m_Home_Button.Name = "m_Home_Button";
            this.m_Home_Button.RequiresTransparency = true;
            this.m_Home_Button.ScreenOwnerName = "Drying_Screen";
            this.m_Home_Button.StyleName = "Vintage";
            this.m_Home_Button.SymbolHeight = 36;
            this.m_Home_Button.SymbolIntervalMapper = symbolintervalmapper7;
            this.m_Home_Button.SymbolName = "home (1)";
            this.m_Home_Button.SymbolWidth = 40;
            this.m_Home_Button.TextHeight = 22;
            this.m_Home_Button.TextValue = 0D;
            this.m_Home_Button.TextWidth = 91;
            this.m_Home_Button.Top = 0;
            this.m_Home_Button.Value = 0D;
            this.m_Home_Button.VisibleDynamicsValue = true;
            this.m_Home_Button.VisualPropertiesHashCode = 1775881799;
            this.m_Home_Button.Width = 97;
            // 
            // m_Auto_Button
            // 
            this.m_Auto_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(49)))), ((int)(((byte)(146))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Auto_Button.BlinkDynamicsValue = false;
            this.m_Auto_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Auto_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 5D, 5D, 0D);
            this.m_Auto_Button.DelayMouseInputPeriod = 0;
            this.m_Auto_Button.EnabledDynamicsValue = true;
            this.m_Auto_Button.FontSizePixels = 16;
            this.m_Auto_Button.ForceTransparency = true;
            this.m_Auto_Button.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Auto_Button.Height = 58;
            this.m_Auto_Button.IndicatorMargin = null;
            this.m_Auto_Button.Left = 105;
            this.m_Auto_Button.MultiLine = true;
            this.m_Auto_Button.Name = "m_Auto_Button";
            this.m_Auto_Button.RequiresTransparency = true;
            this.m_Auto_Button.ScreenOwnerName = "Drying_Screen";
            this.m_Auto_Button.StyleName = "Vintage";
            this.m_Auto_Button.SymbolIntervalMapper = symbolintervalmapper8;
            this.m_Auto_Button.TextHeight = 38;
            this.m_Auto_Button.TextValue = 0D;
            this.m_Auto_Button.TextWidth = 91;
            this.m_Auto_Button.Top = 0;
            this.m_Auto_Button.Value = 0D;
            this.m_Auto_Button.VisibleDynamicsValue = true;
            this.m_Auto_Button.VisualPropertiesHashCode = -475964534;
            this.m_Auto_Button.Width = 97;
            // 
            // m_Manuel_Button
            // 
            this.m_Manuel_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(49)))), ((int)(((byte)(146))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Manuel_Button.BlinkDynamicsValue = false;
            this.m_Manuel_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Manuel_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 5D, 5D, 0D);
            this.m_Manuel_Button.DelayMouseInputPeriod = 0;
            this.m_Manuel_Button.EnabledDynamicsValue = true;
            this.m_Manuel_Button.FontSizePixels = 16;
            this.m_Manuel_Button.ForceTransparency = true;
            this.m_Manuel_Button.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Manuel_Button.Height = 58;
            this.m_Manuel_Button.IndicatorMargin = null;
            this.m_Manuel_Button.Left = 209;
            this.m_Manuel_Button.MultiLine = true;
            this.m_Manuel_Button.Name = "m_Manuel_Button";
            this.m_Manuel_Button.RequiresTransparency = true;
            this.m_Manuel_Button.ScreenOwnerName = "Drying_Screen";
            this.m_Manuel_Button.StyleName = "Vintage";
            this.m_Manuel_Button.SymbolIntervalMapper = symbolintervalmapper9;
            this.m_Manuel_Button.TextHeight = 38;
            this.m_Manuel_Button.TextValue = 0D;
            this.m_Manuel_Button.TextWidth = 91;
            this.m_Manuel_Button.Top = 0;
            this.m_Manuel_Button.Value = 0D;
            this.m_Manuel_Button.VisibleDynamicsValue = true;
            this.m_Manuel_Button.VisualPropertiesHashCode = -475964534;
            this.m_Manuel_Button.Width = 97;
            // 
            // m_Alarm_button
            // 
            this.m_Alarm_button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(49)))), ((int)(((byte)(146))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Alarm_button.BlinkDynamicsValue = false;
            this.m_Alarm_button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Alarm_button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 5D, 5D, 0D);
            this.m_Alarm_button.DelayMouseInputPeriod = 0;
            this.m_Alarm_button.EnabledDynamicsValue = true;
            this.m_Alarm_button.FontSizePixels = 16;
            this.m_Alarm_button.ForceTransparency = true;
            this.m_Alarm_button.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Alarm_button.Height = 58;
            this.m_Alarm_button.IndicatorMargin = null;
            this.m_Alarm_button.Left = 523;
            this.m_Alarm_button.MultiLine = true;
            this.m_Alarm_button.Name = "m_Alarm_button";
            this.m_Alarm_button.RequiresTransparency = true;
            this.m_Alarm_button.ScreenOwnerName = "Drying_Screen";
            this.m_Alarm_button.StyleName = "Vintage";
            this.m_Alarm_button.SymbolIntervalMapper = symbolintervalmapper10;
            this.m_Alarm_button.TextHeight = 38;
            this.m_Alarm_button.TextValue = 0D;
            this.m_Alarm_button.TextWidth = 91;
            this.m_Alarm_button.Top = 0;
            this.m_Alarm_button.Value = 0D;
            this.m_Alarm_button.VisibleDynamicsValue = true;
            this.m_Alarm_button.VisualPropertiesHashCode = -475964534;
            this.m_Alarm_button.Width = 97;
            // 
            // m_Rectangle
            // 
            this.m_Rectangle.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(5, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_Rectangle.BlinkDynamicsValue = false;
            this.m_Rectangle.DelayMouseInputPeriod = 0;
            this.m_Rectangle.EnabledDynamicsValue = true;
            this.m_Rectangle.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Rectangle.Height = 420;
            this.m_Rectangle.Left = 0;
            this.m_Rectangle.Name = "m_Rectangle";
            this.m_Rectangle.ScreenOwnerName = "Drying_Screen";
            this.m_Rectangle.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle.StrokeThickness = 10;
            this.m_Rectangle.Top = 53;
            this.m_Rectangle.VisibleDynamicsValue = true;
            this.m_Rectangle.Width = 800;
            // 
            // m_Drying_Button
            // 
            this.m_Drying_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Drying_Button.BlinkDynamicsValue = false;
            this.m_Drying_Button.Bold = true;
            this.m_Drying_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Drying_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 5D, 5D, 0D);
            this.m_Drying_Button.DelayMouseInputPeriod = 0;
            this.m_Drying_Button.EnabledDynamicsValue = true;
            this.m_Drying_Button.FontSizePixels = 16;
            this.m_Drying_Button.ForceTransparency = true;
            this.m_Drying_Button.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(49)))), ((int)(((byte)(146)))));
            this.m_Drying_Button.Height = 58;
            this.m_Drying_Button.IndicatorMargin = null;
            this.m_Drying_Button.Left = 417;
            this.m_Drying_Button.Name = "m_Drying_Button";
            this.m_Drying_Button.RequiresTransparency = true;
            this.m_Drying_Button.ScreenOwnerName = "Drying_Screen";
            this.m_Drying_Button.StyleName = "Vintage";
            this.m_Drying_Button.SymbolIntervalMapper = symbolintervalmapper11;
            this.m_Drying_Button.TextHeight = 19;
            this.m_Drying_Button.TextValue = 0D;
            this.m_Drying_Button.TextWidth = 91;
            this.m_Drying_Button.Top = 0;
            this.m_Drying_Button.Value = 0D;
            this.m_Drying_Button.VisibleDynamicsValue = true;
            this.m_Drying_Button.VisualPropertiesHashCode = 188522111;
            this.m_Drying_Button.Width = 97;
            // 
            // m_DigitalClock3
            // 
            this.m_DigitalClock3.BlinkDynamicsValue = false;
            this.m_DigitalClock3.Bold = true;
            this.m_DigitalClock3.DelayMouseInputPeriod = 0;
            this.m_DigitalClock3.DisplayFormat = Neo.ApplicationFramework.Interfaces.DateTimeDisplayFormat.Date;
            this.m_DigitalClock3.EnabledDynamicsValue = true;
            this.m_DigitalClock3.FontSizePixels = 18;
            this.m_DigitalClock3.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_DigitalClock3.Height = 29;
            this.m_DigitalClock3.Left = 0;
            this.m_DigitalClock3.Name = "m_DigitalClock3";
            this.m_DigitalClock3.ScreenOwnerName = "Drying_Screen";
            this.m_DigitalClock3.ShowDayOfWeek = false;
            this.m_DigitalClock3.ShowSeconds = true;
            this.m_DigitalClock3.Text = "28.08.2019";
            this.m_DigitalClock3.Top = 0;
            this.m_DigitalClock3.VisibleDynamicsValue = true;
            this.m_DigitalClock3.Width = 166;
            // 
            // m_DigitalClock4
            // 
            this.m_DigitalClock4.BlinkDynamicsValue = false;
            this.m_DigitalClock4.Bold = true;
            this.m_DigitalClock4.DelayMouseInputPeriod = 0;
            this.m_DigitalClock4.DisplayFormat = Neo.ApplicationFramework.Interfaces.DateTimeDisplayFormat.Time;
            this.m_DigitalClock4.EnabledDynamicsValue = true;
            this.m_DigitalClock4.FontSizePixels = 18;
            this.m_DigitalClock4.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_DigitalClock4.Height = 29;
            this.m_DigitalClock4.Left = 6;
            this.m_DigitalClock4.Name = "m_DigitalClock4";
            this.m_DigitalClock4.ScreenOwnerName = "Drying_Screen";
            this.m_DigitalClock4.ShowDayOfWeek = false;
            this.m_DigitalClock4.ShowSeconds = true;
            this.m_DigitalClock4.Text = "17:28:45";
            this.m_DigitalClock4.Top = 20;
            this.m_DigitalClock4.VisibleDynamicsValue = true;
            this.m_DigitalClock4.Width = 143;
            // 
            // m_DateClock
            // 
            this.m_DateClock.BlinkDynamicsValue = false;
            this.m_DateClock.Components.Add(this.m_DigitalClock3);
            this.m_DateClock.Components.Add(this.m_DigitalClock4);
            this.m_DateClock.DelayMouseInputPeriod = 0;
            this.m_DateClock.EnabledDynamicsValue = true;
            this.m_DateClock.Height = 46;
            this.m_DateClock.Left = 643;
            this.m_DateClock.Name = "m_DateClock";
            // 
            // m_Navigation
            // 
            this.m_Navigation.BlinkDynamicsValue = false;
            this.m_Navigation.Components.Add(this.m_Test_Nav);
            this.m_Navigation.Components.Add(this.m_Home_Button);
            this.m_Navigation.Components.Add(this.m_Auto_Button);
            this.m_Navigation.Components.Add(this.m_Manuel_Button);
            this.m_Navigation.Components.Add(this.m_Alarm_button);
            this.m_Navigation.Components.Add(this.m_Rectangle);
            this.m_Navigation.Components.Add(this.m_Drying_Button);
            this.m_Navigation.Components.Add(this.m_DateClock);
            this.m_Navigation.DelayMouseInputPeriod = 0;
            this.m_Navigation.EnabledDynamicsValue = true;
            this.m_Navigation.Height = 473;
            this.m_Navigation.Left = 0;
            this.m_Navigation.Name = "m_Navigation";
            this.m_Navigation.ParentGroup = null;
            this.m_Navigation.ScreenOwnerName = "Drying_Screen";
            this.m_Navigation.Top = 7;
            this.m_Navigation.VisibleDynamicsValue = true;
            this.m_Navigation.Width = 800;
            this.m_DateClock.ParentGroup = this.m_Navigation;
            this.m_DateClock.ScreenOwnerName = "Drying_Screen";
            this.m_DateClock.Top = 6;
            this.m_DateClock.VisibleDynamicsValue = true;
            this.m_DateClock.Width = 128;
            // 
            // m_Lamp_Switch
            // 
            this.m_Lamp_Switch.BlinkDynamicsValue = false;
            this.m_Lamp_Switch.DelayMouseInputPeriod = 0;
            this.m_Lamp_Switch.EnabledDynamicsValue = true;
            this.m_Lamp_Switch.Height = 93;
            this.m_Lamp_Switch.Left = 679;
            this.m_Lamp_Switch.Name = "m_Lamp_Switch";
            this.m_Lamp_Switch.ScreenOwnerName = "Drying_Screen";
            this.m_Lamp_Switch.Stretch = true;
            multisymbolitem1.SymbolName = "light close";
            multisymbolitem1.Transparent = false;
            symbolinterval1.Value = multisymbolitem1;
            symbolinterval2.End = 1D;
            symbolinterval2.Start = 1D;
            multisymbolitem2.SymbolName = "light open";
            multisymbolitem2.Transparent = false;
            symbolinterval2.Value = multisymbolitem2;
            symbolintervalmapper12.Intervals.Add(symbolinterval1);
            symbolintervalmapper12.Intervals.Add(symbolinterval2);
            this.m_Lamp_Switch.SymbolIntervalMapper = symbolintervalmapper12;
            this.m_Lamp_Switch.SymbolName = "light close";
            this.m_Lamp_Switch.Top = 369;
            this.m_Lamp_Switch.Value = 0D;
            this.m_Lamp_Switch.VisibleDynamicsValue = true;
            this.m_Lamp_Switch.Width = 93;
            // 
            // m_Text4
            // 
            this.m_Text4.BlinkDynamicsValue = false;
            this.m_Text4.DelayMouseInputPeriod = 0;
            this.m_Text4.EnabledDynamicsValue = true;
            this.m_Text4.FontSizePixels = 20;
            this.m_Text4.Height = 21;
            this.m_Text4.Left = 633;
            this.m_Text4.Name = "m_Text4";
            this.m_Text4.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 0D, 5D, 1D);
            this.m_Text4.ScreenOwnerName = "Drying_Screen";
            this.m_Text4.Top = 7;
            this.m_Text4.Visible = false;
            this.m_Text4.Width = 51;
            // 
            // m_Text2
            // 
            this.m_Text2.BlinkDynamicsValue = false;
            this.m_Text2.DelayMouseInputPeriod = 0;
            this.m_Text2.EnabledDynamicsValue = true;
            this.m_Text2.FontSizePixels = 20;
            this.m_Text2.Height = 21;
            this.m_Text2.Left = 597;
            this.m_Text2.Name = "m_Text2";
            this.m_Text2.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 0D, 5D, 1D);
            this.m_Text2.ScreenOwnerName = "Drying_Screen";
            this.m_Text2.Top = 32;
            this.m_Text2.Visible = false;
            this.m_Text2.Width = 155;
            // 
            // m_Drying_Heat_Text
            // 
            this.m_Drying_Heat_Text.AutoSize = false;
            this.m_Drying_Heat_Text.BlinkDynamicsValue = false;
            this.m_Drying_Heat_Text.Bold = true;
            this.m_Drying_Heat_Text.DelayMouseInputPeriod = 0;
            this.m_Drying_Heat_Text.EnabledDynamicsValue = true;
            this.m_Drying_Heat_Text.FontSizePixels = 18;
            this.m_Drying_Heat_Text.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Drying_Heat_Text.Height = 39;
            this.m_Drying_Heat_Text.Left = 19;
            this.m_Drying_Heat_Text.Name = "m_Drying_Heat_Text";
            this.m_Drying_Heat_Text.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(4.5D, 0D, 4.5D, 1D);
            this.m_Drying_Heat_Text.ScreenOwnerName = "Drying_Screen";
            this.m_Drying_Heat_Text.Top = 225;
            this.m_Drying_Heat_Text.VisibleDynamicsValue = true;
            this.m_Drying_Heat_Text.Width = 281;
            // 
            // m_Drying_Heat_Set
            // 
            this.m_Drying_Heat_Set.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_Drying_Heat_Set.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_Drying_Heat_Set.BlinkDynamicsValue = false;
            this.m_Drying_Heat_Set.Bold = true;
            this.m_Drying_Heat_Set.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Drying_Heat_Set.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Drying_Heat_Set.DelayMouseInputPeriod = 0;
            this.m_Drying_Heat_Set.EnabledDynamicsValue = true;
            this.m_Drying_Heat_Set.FontSizePixels = 18;
            this.m_Drying_Heat_Set.Height = 39;
            this.m_Drying_Heat_Set.Left = 316;
            this.m_Drying_Heat_Set.MaxValue = 110D;
            this.m_Drying_Heat_Set.MinValue = 80D;
            this.m_Drying_Heat_Set.Name = "m_Drying_Heat_Set";
            this.m_Drying_Heat_Set.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Drying_Heat_Set.ScreenOwnerName = "Drying_Screen";
            this.m_Drying_Heat_Set.Top = 225;
            this.m_Drying_Heat_Set.ValidateValueOnInput = true;
            this.m_Drying_Heat_Set.VisibleDynamicsValue = true;
            this.m_Drying_Heat_Set.Width = 164;
            // 
            // m_Current_Heat_Text
            // 
            this.m_Current_Heat_Text.AutoSize = false;
            this.m_Current_Heat_Text.BlinkDynamicsValue = false;
            this.m_Current_Heat_Text.Bold = true;
            this.m_Current_Heat_Text.DelayMouseInputPeriod = 0;
            this.m_Current_Heat_Text.EnabledDynamicsValue = true;
            this.m_Current_Heat_Text.FontSizePixels = 18;
            this.m_Current_Heat_Text.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Current_Heat_Text.Height = 39;
            this.m_Current_Heat_Text.Left = 19;
            this.m_Current_Heat_Text.Name = "m_Current_Heat_Text";
            this.m_Current_Heat_Text.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(4.5D, 0D, 4.5D, 1D);
            this.m_Current_Heat_Text.ScreenOwnerName = "Drying_Screen";
            this.m_Current_Heat_Text.Top = 269;
            this.m_Current_Heat_Text.VisibleDynamicsValue = true;
            this.m_Current_Heat_Text.Width = 281;
            // 
            // m_Current_Heat
            // 
            this.m_Current_Heat.BlinkDynamicsValue = false;
            this.m_Current_Heat.Bold = true;
            this.m_Current_Heat.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Current_Heat.DelayMouseInputPeriod = 0;
            this.m_Current_Heat.DisplayFormat = Neo.ApplicationFramework.Interfaces.AnalogNumericDisplayFormat.Decimal;
            this.m_Current_Heat.EnabledDynamicsValue = true;
            this.m_Current_Heat.FontSizePixels = 18;
            this.m_Current_Heat.Height = 39;
            this.m_Current_Heat.Left = 316;
            this.m_Current_Heat.Name = "m_Current_Heat";
            this.m_Current_Heat.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Current_Heat.ReadOnly = true;
            this.m_Current_Heat.ScreenOwnerName = "Drying_Screen";
            this.m_Current_Heat.Top = 269;
            this.m_Current_Heat.VisibleDynamicsValue = true;
            this.m_Current_Heat.Width = 164;
            // 
            // m_Text
            // 
            this.m_Text.BlinkDynamicsValue = false;
            this.m_Text.DelayMouseInputPeriod = 0;
            this.m_Text.EnabledDynamicsValue = true;
            this.m_Text.FontSizePixels = 20;
            this.m_Text.Height = 21;
            this.m_Text.Left = 608;
            this.m_Text.Name = "m_Text";
            this.m_Text.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 0D, 5D, 1D);
            this.m_Text.ScreenOwnerName = "Drying_Screen";
            this.m_Text.Top = 97;
            this.m_Text.Visible = false;
            this.m_Text.Width = 207;
            // 
            // m_Text1
            // 
            this.m_Text1.BlinkDynamicsValue = false;
            this.m_Text1.Bold = true;
            this.m_Text1.DelayMouseInputPeriod = 0;
            this.m_Text1.EnabledDynamicsValue = true;
            this.m_Text1.FontSizePixels = 16;
            this.m_Text1.Height = 34;
            this.m_Text1.Italic = true;
            this.m_Text1.Left = 490;
            this.m_Text1.MultiLine = true;
            this.m_Text1.Name = "m_Text1";
            this.m_Text1.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(4D, 0D, 4D, 1D);
            this.m_Text1.ScreenOwnerName = "Drying_Screen";
            this.m_Text1.Top = 222;
            this.m_Text1.VisibleDynamicsValue = true;
            this.m_Text1.Width = 51;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "Drying_Screen";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_Drying_Screen = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_Drying_Screen) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_Logo);
            this.DrawingPrimitives.Add(this.m_Drying_Status);
            this.DrawingPrimitives.Add(this.m_Drying_Start);
            this.DrawingPrimitives.Add(this.m_Drying_Time_Text);
            this.DrawingPrimitives.Add(this.m_Drying_Min_Set);
            this.DrawingPrimitives.Add(this.m_Stable_Down);
            this.DrawingPrimitives.Add(this.m_Button4);
            this.DrawingPrimitives.Add(this.m_Filter_Stabilizer_Control);
            this.DrawingPrimitives.Add(this.m_Door_Open_Button);
            this.DrawingPrimitives.Add(this.m_Door_Close_Button);
            this.DrawingPrimitives.Add(this.m_Door_Control);
            this.DrawingPrimitives.Add(this.m_Test_Nav);
            this.DrawingPrimitives.Add(this.m_Home_Button);
            this.DrawingPrimitives.Add(this.m_Auto_Button);
            this.DrawingPrimitives.Add(this.m_Manuel_Button);
            this.DrawingPrimitives.Add(this.m_Alarm_button);
            this.DrawingPrimitives.Add(this.m_Rectangle);
            this.DrawingPrimitives.Add(this.m_Drying_Button);
            this.DrawingPrimitives.Add(this.m_DigitalClock3);
            this.DrawingPrimitives.Add(this.m_DigitalClock4);
            this.DrawingPrimitives.Add(this.m_DateClock);
            this.DrawingPrimitives.Add(this.m_Navigation);
            this.DrawingPrimitives.Add(this.m_Lamp_Switch);
            this.DrawingPrimitives.Add(this.m_Text4);
            this.DrawingPrimitives.Add(this.m_Text2);
            this.DrawingPrimitives.Add(this.m_Drying_Heat_Text);
            this.DrawingPrimitives.Add(this.m_Drying_Heat_Set);
            this.DrawingPrimitives.Add(this.m_Current_Heat_Text);
            this.DrawingPrimitives.Add(this.m_Current_Heat);
            this.DrawingPrimitives.Add(this.m_Text);
            this.DrawingPrimitives.Add(this.m_Text1);
            ((System.ComponentModel.ISupportInitialize)(this.m_Logo)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Drying_Start)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Drying_Time_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Drying_Min_Set)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Stable_Down)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Filter_Stabilizer_Control)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Door_Open_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Door_Close_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Door_Control)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Test_Nav)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Home_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Auto_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Manuel_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Alarm_button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Drying_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_DigitalClock3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_DigitalClock4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Navigation)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_DateClock)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Lamp_Switch)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Drying_Heat_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Drying_Heat_Set)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Current_Heat_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Current_Heat)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).EndInit();
        }
        
        private void m_Stable_Down_Action_PreviewMouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Stable_Down", "MouseDown", "Set Tag", "Tags.Piston_Down", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Piston_Down.SetTag();
        }
        
        private void m_Stable_Down_Action_PreviewMouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Stable_Down", "MouseUp", "Reset Tag", "Tags.Piston_Down", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Piston_Down.ResetTag();
        }
        
        private void m_Button4_Action_PreviewMouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button4", "MouseDown", "Set Tag", "Tags.Piston_Up", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Piston_Up.SetTag();
        }
        
        private void m_Button4_Action_PreviewMouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button4", "MouseUp", "Reset Tag", "Tags.Piston_Up", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Piston_Up.ResetTag();
        }
        
        private void m_Door_Open_Button_Action_PreviewMouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Door_Open_Button", "MouseDown", "Set Tag", "Tags.Door_Open", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Door_Open.SetTag();
        }
        
        private void m_Door_Open_Button_Action_PreviewMouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Door_Open_Button", "MouseUp", "Reset Tag", "Tags.Door_Open", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Door_Open.ResetTag();
        }
        
        private void m_Door_Close_Button_Action_PreviewMouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Door_Close_Button", "MouseDown", "Set Tag", "Tags.Door_Close", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Door_Close.SetTag();
        }
        
        private void m_Door_Close_Button_Action_PreviewMouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Door_Close_Button", "MouseUp", "Reset Tag", "Tags.Door_Close", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Door_Close.ResetTag();
        }
        
        private void m_Test_Nav_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Test_Nav", "Click", "Show Screen", "Test_Screen", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.Test_Screen.Show();
        }
        
        private void m_Home_Button_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Home_Button", "Click", "Show Screen", "HomeScreen", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.HomeScreen.Show();
        }
        
        private void m_Auto_Button_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Auto_Button", "Click", "Show Screen", "Automatic_Screen", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.Automatic_Screen.Show();
        }
        
        private void m_Manuel_Button_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Manuel_Button", "Click", "Show Screen", "Manuel_Screen", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.Manuel_Screen.Show();
        }
        
        private void m_Alarm_button_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Alarm_button", "Click", "Show Screen", "Alarm_Screen", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.Alarm_Screen.Show();
        }
        
        private void m_Lamp_Switch_Action_MouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Lamp_Switch", "MouseDown", "Toggle Tag", "Tags.Interior_Lightning", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Interior_Lightning.ToggleTag();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Drying_Screen));
            this.m_Drying_Start.Text = resources.GetText("Drying_Screen.Drying_Start.Text", "DRYING");
            this.m_Drying_Time_Text.Text = resources.GetText("Drying_Screen.Drying_Time_Text.Text", "DRYING TIME");
            this.m_Drying_Min_Set.Prefix = resources.GetText("Drying_Screen.Drying_Min_Set.Prefix", "SET: ");
            this.m_Drying_Min_Set.Suffix = resources.GetText("Drying_Screen.Drying_Min_Set.Suffix", " min.");
            this.m_Door_Open_Button.Text = resources.GetText("Drying_Screen.Door_Open_Button.Text", "OPEN DOOR");
            this.m_Door_Close_Button.Text = resources.GetText("Drying_Screen.Door_Close_Button.Text", "CLOSE DOOR");
            this.m_Stable_Down.Text = resources.GetText("Drying_Screen.Stable_Down.Text", "FILTER STABILIZER\r\nDOWN");
            this.m_Button4.Text = resources.GetText("Drying_Screen.Button4.Text", "FILTER STABILIZER\r\nUP");
            this.m_Auto_Button.Text = resources.GetText("Drying_Screen.Auto_Button.Text", "Automatic\r\nWashing");
            this.m_Manuel_Button.Text = resources.GetText("Drying_Screen.Manuel_Button.Text", "Manuel\r\nWashing");
            this.m_Alarm_button.Text = resources.GetText("Drying_Screen.Alarm_button.Text", "Alarm\r\nScreen");
            this.m_Drying_Button.Text = resources.GetText("Drying_Screen.Drying_Button.Text", "Drying");
            this.m_Test_Nav.Text = resources.GetText("Drying_Screen.Test_Nav.Text", "Test");
            this.m_Text4.Text = resources.GetText("Drying_Screen.Text4.Text", "Warning!");
            this.m_Text2.Text = resources.GetText("Drying_Screen.Text2.Text", "Please Enter the Drying Time!");
            this.m_Drying_Heat_Text.Text = resources.GetText("Drying_Screen.Drying_Heat_Text.Text", "DRYING TEMPERATURE");
            this.m_Drying_Heat_Set.Prefix = resources.GetText("Drying_Screen.Drying_Heat_Set.Prefix", "SET: ");
            this.m_Drying_Heat_Set.Suffix = resources.GetText("Drying_Screen.Drying_Heat_Set.Suffix", " C");
            this.m_Current_Heat_Text.Text = resources.GetText("Drying_Screen.Current_Heat_Text.Text", "CURRENT DRYING TEMP.");
            this.m_Current_Heat.Suffix = resources.GetText("Drying_Screen.Current_Heat.Suffix", " C");
            this.m_Text.Text = resources.GetText("Drying_Screen.Text.Text", "Please Enter a Valid Temperature Value!");
            this.m_Text1.Text = resources.GetText("Drying_Screen.Text1.Text", "Value:\r\n80-110 C");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage() {
            this.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_Drying_Screen) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Fill", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Drying_Proc"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf1);
            this.m_Drying_Status.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Drying_Proc"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Drying_Start.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding3 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Foreground", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Drying_Proc"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf2);
            this.m_Drying_Start.DataBindings.Add(dynamicBinding3);
            this.m_DynamicBindings.Add(dynamicBinding3);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding4 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Drying_Time"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Drying_Min_Set.DataBindings.Add(dynamicBinding4);
            this.m_DynamicBindings.Add(dynamicBinding4);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding5 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("ReadOnly", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Drying_Proc"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Drying_Min_Set.DataBindings.Add(dynamicBinding5);
            this.m_DynamicBindings.Add(dynamicBinding5);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding6 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("EnabledDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Automatic_Washing"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueZero);
            this.m_Test_Nav.DataBindings.Add(dynamicBinding6);
            this.m_DynamicBindings.Add(dynamicBinding6);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding7 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("EnabledDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Drying_Proc"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueZero);
            this.m_Manuel_Button.DataBindings.Add(dynamicBinding7);
            this.m_DynamicBindings.Add(dynamicBinding7);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding8 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Interior_Lightning"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Lamp_Switch.DataBindings.Add(dynamicBinding8);
            this.m_DynamicBindings.Add(dynamicBinding8);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding9 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Air_Heater_Set"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Drying_Heat_Set.DataBindings.Add(dynamicBinding9);
            this.m_DynamicBindings.Add(dynamicBinding9);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding10 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Current_Air_Heater"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Current_Heat.DataBindings.Add(dynamicBinding10);
            this.m_DynamicBindings.Add(dynamicBinding10);
        }
    }
}
