//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class HomeScreen : Neo.ApplicationFramework.Controls.Controls.Form, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage {
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Logo;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_KSPFull;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_HSEnglishFlag;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Date_Time;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture1;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_prewashWaterTime_Num;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_prewashRestTime_Num;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_dryingAirTime_Num;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_dryingRestTime_Num;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_cleaningWaterTime_Num;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_cleaningPressTime_Num;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_cleaningRestTime_Num;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_testTime_Num;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric1;
        
        private Neo.ApplicationFramework.Controls.Controls.GroupCF m_Group1;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric2;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_an_WaterLevel;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric3;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric4;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture4;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture5;
        
        private bool m_Initialized_HomeScreen;
        
        public HomeScreen() {
            this.InitializeComponent();
            this.Adapter.Closed += new System.EventHandler(this.HomeScreen_Closed);
            this.m_HSEnglishFlag.MouseDown += new System.EventHandler(this.m_HSEnglishFlag_Action_MouseDown);
            this.m_Date_Time.MouseDown += new System.EventHandler(this.m_Date_Time_Action_MouseDown);
            this.m_Picture1.MouseDown += new System.EventHandler(this.m_Picture1_Action_MouseDown);
            this.m_Picture4.MouseDown += new System.EventHandler(this.m_Picture4_Action_MouseDown);
            this.m_Picture5.MouseDown += new System.EventHandler(this.m_Picture5_Action_MouseDown);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Logo {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Logo);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter KSPFull {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_KSPFull);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter HSEnglishFlag {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_HSEnglishFlag);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Date_Time {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Date_Time);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.GroupCFAdapter Group1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.GroupCFAdapter>(this.m_Group1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter prewashWaterTime_Num {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_prewashWaterTime_Num);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter prewashRestTime_Num {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_prewashRestTime_Num);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter dryingAirTime_Num {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_dryingAirTime_Num);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter dryingRestTime_Num {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_dryingRestTime_Num);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter cleaningWaterTime_Num {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_cleaningWaterTime_Num);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter cleaningPressTime_Num {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_cleaningPressTime_Num);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter cleaningRestTime_Num {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_cleaningRestTime_Num);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter testTime_Num {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_testTime_Num);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter an_WaterLevel {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_an_WaterLevel);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture5);
            }
        }
        
        private void InitializeComponent() {
            this.m_Logo = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_KSPFull = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_HSEnglishFlag = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Date_Time = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Picture1 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_prewashWaterTime_Num = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_prewashRestTime_Num = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_dryingAirTime_Num = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_dryingRestTime_Num = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_cleaningWaterTime_Num = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_cleaningPressTime_Num = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_cleaningRestTime_Num = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_testTime_Num = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_AnalogNumeric = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_AnalogNumeric1 = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_Group1 = new Neo.ApplicationFramework.Controls.Controls.GroupCF();
            this.m_AnalogNumeric2 = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_an_WaterLevel = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_AnalogNumeric3 = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_AnalogNumeric4 = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_Picture4 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Picture5 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            ((System.ComponentModel.ISupportInitialize)(this.m_Logo)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_KSPFull)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_HSEnglishFlag)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Date_Time)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_prewashWaterTime_Num)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_prewashRestTime_Num)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_dryingAirTime_Num)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_dryingRestTime_Num)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_cleaningWaterTime_Num)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_cleaningPressTime_Num)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_cleaningRestTime_Num)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_testTime_Num)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Group1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_an_WaterLevel)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture5)).BeginInit();
            this.SuspendLayout();
            // 
            // HomeScreen
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(130)))), ((int)(((byte)(31))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.ThreeDBorder;
            this.ControlBox = false;
            // 
            // m_Logo
            // 
            this.m_Logo.BlinkDynamicsValue = false;
            this.m_Logo.DelayMouseInputPeriod = 0;
            this.m_Logo.EnabledDynamicsValue = true;
            this.m_Logo.Height = 482;
            this.m_Logo.Left = 464;
            this.m_Logo.Name = "m_Logo";
            this.m_Logo.ScreenOwnerName = "HomeScreen";
            this.m_Logo.Stretch = true;
            this.m_Logo.SymbolName = "logobeyaz";
            this.m_Logo.Top = 17;
            this.m_Logo.VisibleDynamicsValue = true;
            this.m_Logo.Width = 475;
            // 
            // m_KSPFull
            // 
            this.m_KSPFull.BlinkDynamicsValue = false;
            this.m_KSPFull.DelayMouseInputPeriod = 0;
            this.m_KSPFull.EnabledDynamicsValue = true;
            this.m_KSPFull.Height = 112;
            this.m_KSPFull.Left = 237;
            this.m_KSPFull.Name = "m_KSPFull";
            this.m_KSPFull.ScreenOwnerName = "HomeScreen";
            this.m_KSPFull.Stretch = true;
            this.m_KSPFull.SymbolName = "logowname (2)";
            this.m_KSPFull.Top = 322;
            this.m_KSPFull.VisibleDynamicsValue = true;
            this.m_KSPFull.Width = 317;
            // 
            // m_HSEnglishFlag
            // 
            this.m_HSEnglishFlag.BlinkDynamicsValue = false;
            this.m_HSEnglishFlag.DelayMouseInputPeriod = 0;
            this.m_HSEnglishFlag.EnabledDynamicsValue = true;
            this.m_HSEnglishFlag.Height = 120;
            this.m_HSEnglishFlag.Left = 550;
            this.m_HSEnglishFlag.Name = "m_HSEnglishFlag";
            this.m_HSEnglishFlag.ScreenOwnerName = "HomeScreen";
            this.m_HSEnglishFlag.Stretch = true;
            this.m_HSEnglishFlag.SymbolName = "united-kingdom-flag-3d-round-icon-256";
            this.m_HSEnglishFlag.Top = 100;
            this.m_HSEnglishFlag.VisibleDynamicsValue = true;
            this.m_HSEnglishFlag.Width = 120;
            // 
            // m_Date_Time
            // 
            this.m_Date_Time.BlinkDynamicsValue = false;
            this.m_Date_Time.DelayMouseInputPeriod = 0;
            this.m_Date_Time.EnabledDynamicsValue = true;
            this.m_Date_Time.Height = 70;
            this.m_Date_Time.Left = 48;
            this.m_Date_Time.Name = "m_Date_Time";
            this.m_Date_Time.ScreenOwnerName = "HomeScreen";
            this.m_Date_Time.Stretch = true;
            this.m_Date_Time.SymbolName = "d&t";
            this.m_Date_Time.Top = 343;
            this.m_Date_Time.VisibleDynamicsValue = true;
            this.m_Date_Time.Width = 70;
            // 
            // m_Picture1
            // 
            this.m_Picture1.BlinkDynamicsValue = false;
            this.m_Picture1.DelayMouseInputPeriod = 0;
            this.m_Picture1.EnabledDynamicsValue = true;
            this.m_Picture1.Height = 120;
            this.m_Picture1.Left = 130;
            this.m_Picture1.Name = "m_Picture1";
            this.m_Picture1.ScreenOwnerName = "HomeScreen";
            this.m_Picture1.Stretch = true;
            this.m_Picture1.SymbolName = "spain-flag-3d-round-icon-256";
            this.m_Picture1.Top = 100;
            this.m_Picture1.VisibleDynamicsValue = true;
            this.m_Picture1.Width = 120;
            // 
            // m_prewashWaterTime_Num
            // 
            this.m_prewashWaterTime_Num.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_prewashWaterTime_Num.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_prewashWaterTime_Num.BlinkDynamicsValue = false;
            this.m_prewashWaterTime_Num.Bold = true;
            this.m_prewashWaterTime_Num.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_prewashWaterTime_Num.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_prewashWaterTime_Num.DelayMouseInputPeriod = 0;
            this.m_prewashWaterTime_Num.EnabledDynamicsValue = true;
            this.m_prewashWaterTime_Num.FontSizePixels = 20;
            this.m_prewashWaterTime_Num.Height = 35;
            this.m_prewashWaterTime_Num.Left = 561;
            this.m_prewashWaterTime_Num.MaxNumberOfCharacters = 3;
            this.m_prewashWaterTime_Num.MaxValue = 5000D;
            this.m_prewashWaterTime_Num.MinValue = 1D;
            this.m_prewashWaterTime_Num.Name = "m_prewashWaterTime_Num";
            this.m_prewashWaterTime_Num.NumberOfDecimals = 0;
            this.m_prewashWaterTime_Num.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_prewashWaterTime_Num.ReadOnly = true;
            this.m_prewashWaterTime_Num.ScreenOwnerName = "HomeScreen";
            this.m_prewashWaterTime_Num.Top = 61;
            this.m_prewashWaterTime_Num.ValidateValueOnInput = true;
            this.m_prewashWaterTime_Num.Visible = false;
            this.m_prewashWaterTime_Num.Width = 150;
            // 
            // m_prewashRestTime_Num
            // 
            this.m_prewashRestTime_Num.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_prewashRestTime_Num.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_prewashRestTime_Num.BlinkDynamicsValue = false;
            this.m_prewashRestTime_Num.Bold = true;
            this.m_prewashRestTime_Num.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_prewashRestTime_Num.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_prewashRestTime_Num.DelayMouseInputPeriod = 0;
            this.m_prewashRestTime_Num.EnabledDynamicsValue = true;
            this.m_prewashRestTime_Num.FontSizePixels = 20;
            this.m_prewashRestTime_Num.Height = 35;
            this.m_prewashRestTime_Num.Left = 561;
            this.m_prewashRestTime_Num.MaxNumberOfCharacters = 3;
            this.m_prewashRestTime_Num.MaxValue = 5000D;
            this.m_prewashRestTime_Num.MinValue = 1D;
            this.m_prewashRestTime_Num.Name = "m_prewashRestTime_Num";
            this.m_prewashRestTime_Num.NumberOfDecimals = 0;
            this.m_prewashRestTime_Num.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_prewashRestTime_Num.ReadOnly = true;
            this.m_prewashRestTime_Num.ScreenOwnerName = "HomeScreen";
            this.m_prewashRestTime_Num.Top = 114;
            this.m_prewashRestTime_Num.ValidateValueOnInput = true;
            this.m_prewashRestTime_Num.Visible = false;
            this.m_prewashRestTime_Num.Width = 150;
            // 
            // m_dryingAirTime_Num
            // 
            this.m_dryingAirTime_Num.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_dryingAirTime_Num.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_dryingAirTime_Num.BlinkDynamicsValue = false;
            this.m_dryingAirTime_Num.Bold = true;
            this.m_dryingAirTime_Num.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_dryingAirTime_Num.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_dryingAirTime_Num.DelayMouseInputPeriod = 0;
            this.m_dryingAirTime_Num.EnabledDynamicsValue = true;
            this.m_dryingAirTime_Num.FontSizePixels = 20;
            this.m_dryingAirTime_Num.Height = 35;
            this.m_dryingAirTime_Num.Left = 561;
            this.m_dryingAirTime_Num.MaxNumberOfCharacters = 3;
            this.m_dryingAirTime_Num.MaxValue = 5000D;
            this.m_dryingAirTime_Num.MinValue = 1D;
            this.m_dryingAirTime_Num.Name = "m_dryingAirTime_Num";
            this.m_dryingAirTime_Num.NumberOfDecimals = 0;
            this.m_dryingAirTime_Num.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_dryingAirTime_Num.ReadOnly = true;
            this.m_dryingAirTime_Num.ScreenOwnerName = "HomeScreen";
            this.m_dryingAirTime_Num.Top = 167;
            this.m_dryingAirTime_Num.ValidateValueOnInput = true;
            this.m_dryingAirTime_Num.Visible = false;
            this.m_dryingAirTime_Num.Width = 150;
            // 
            // m_dryingRestTime_Num
            // 
            this.m_dryingRestTime_Num.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_dryingRestTime_Num.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_dryingRestTime_Num.BlinkDynamicsValue = false;
            this.m_dryingRestTime_Num.Bold = true;
            this.m_dryingRestTime_Num.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_dryingRestTime_Num.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_dryingRestTime_Num.DelayMouseInputPeriod = 0;
            this.m_dryingRestTime_Num.EnabledDynamicsValue = true;
            this.m_dryingRestTime_Num.FontSizePixels = 20;
            this.m_dryingRestTime_Num.Height = 35;
            this.m_dryingRestTime_Num.Left = 561;
            this.m_dryingRestTime_Num.MaxNumberOfCharacters = 3;
            this.m_dryingRestTime_Num.MaxValue = 5000D;
            this.m_dryingRestTime_Num.MinValue = 1D;
            this.m_dryingRestTime_Num.Name = "m_dryingRestTime_Num";
            this.m_dryingRestTime_Num.NumberOfDecimals = 0;
            this.m_dryingRestTime_Num.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_dryingRestTime_Num.ReadOnly = true;
            this.m_dryingRestTime_Num.ScreenOwnerName = "HomeScreen";
            this.m_dryingRestTime_Num.Top = 223;
            this.m_dryingRestTime_Num.ValidateValueOnInput = true;
            this.m_dryingRestTime_Num.Visible = false;
            this.m_dryingRestTime_Num.Width = 150;
            // 
            // m_cleaningWaterTime_Num
            // 
            this.m_cleaningWaterTime_Num.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_cleaningWaterTime_Num.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_cleaningWaterTime_Num.BlinkDynamicsValue = false;
            this.m_cleaningWaterTime_Num.Bold = true;
            this.m_cleaningWaterTime_Num.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_cleaningWaterTime_Num.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_cleaningWaterTime_Num.DelayMouseInputPeriod = 0;
            this.m_cleaningWaterTime_Num.EnabledDynamicsValue = true;
            this.m_cleaningWaterTime_Num.FontSizePixels = 20;
            this.m_cleaningWaterTime_Num.Height = 35;
            this.m_cleaningWaterTime_Num.Left = 561;
            this.m_cleaningWaterTime_Num.MaxNumberOfCharacters = 3;
            this.m_cleaningWaterTime_Num.MaxValue = 5000D;
            this.m_cleaningWaterTime_Num.MinValue = 1D;
            this.m_cleaningWaterTime_Num.Name = "m_cleaningWaterTime_Num";
            this.m_cleaningWaterTime_Num.NumberOfDecimals = 0;
            this.m_cleaningWaterTime_Num.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_cleaningWaterTime_Num.ReadOnly = true;
            this.m_cleaningWaterTime_Num.ScreenOwnerName = "HomeScreen";
            this.m_cleaningWaterTime_Num.Top = 273;
            this.m_cleaningWaterTime_Num.ValidateValueOnInput = true;
            this.m_cleaningWaterTime_Num.Visible = false;
            this.m_cleaningWaterTime_Num.Width = 150;
            // 
            // m_cleaningPressTime_Num
            // 
            this.m_cleaningPressTime_Num.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_cleaningPressTime_Num.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_cleaningPressTime_Num.BlinkDynamicsValue = false;
            this.m_cleaningPressTime_Num.Bold = true;
            this.m_cleaningPressTime_Num.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_cleaningPressTime_Num.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_cleaningPressTime_Num.DelayMouseInputPeriod = 0;
            this.m_cleaningPressTime_Num.EnabledDynamicsValue = true;
            this.m_cleaningPressTime_Num.FontSizePixels = 20;
            this.m_cleaningPressTime_Num.Height = 35;
            this.m_cleaningPressTime_Num.Left = 561;
            this.m_cleaningPressTime_Num.MaxNumberOfCharacters = 3;
            this.m_cleaningPressTime_Num.MaxValue = 5000D;
            this.m_cleaningPressTime_Num.MinValue = 1D;
            this.m_cleaningPressTime_Num.Name = "m_cleaningPressTime_Num";
            this.m_cleaningPressTime_Num.NumberOfDecimals = 0;
            this.m_cleaningPressTime_Num.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_cleaningPressTime_Num.ReadOnly = true;
            this.m_cleaningPressTime_Num.ScreenOwnerName = "HomeScreen";
            this.m_cleaningPressTime_Num.Top = 326;
            this.m_cleaningPressTime_Num.ValidateValueOnInput = true;
            this.m_cleaningPressTime_Num.Visible = false;
            this.m_cleaningPressTime_Num.Width = 150;
            // 
            // m_cleaningRestTime_Num
            // 
            this.m_cleaningRestTime_Num.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_cleaningRestTime_Num.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_cleaningRestTime_Num.BlinkDynamicsValue = false;
            this.m_cleaningRestTime_Num.Bold = true;
            this.m_cleaningRestTime_Num.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_cleaningRestTime_Num.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_cleaningRestTime_Num.DelayMouseInputPeriod = 0;
            this.m_cleaningRestTime_Num.EnabledDynamicsValue = true;
            this.m_cleaningRestTime_Num.FontSizePixels = 20;
            this.m_cleaningRestTime_Num.Height = 35;
            this.m_cleaningRestTime_Num.Left = 561;
            this.m_cleaningRestTime_Num.MaxNumberOfCharacters = 3;
            this.m_cleaningRestTime_Num.MaxValue = 5000D;
            this.m_cleaningRestTime_Num.MinValue = 1D;
            this.m_cleaningRestTime_Num.Name = "m_cleaningRestTime_Num";
            this.m_cleaningRestTime_Num.NumberOfDecimals = 0;
            this.m_cleaningRestTime_Num.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_cleaningRestTime_Num.ReadOnly = true;
            this.m_cleaningRestTime_Num.ScreenOwnerName = "HomeScreen";
            this.m_cleaningRestTime_Num.Top = 379;
            this.m_cleaningRestTime_Num.ValidateValueOnInput = true;
            this.m_cleaningRestTime_Num.Visible = false;
            this.m_cleaningRestTime_Num.Width = 150;
            // 
            // m_testTime_Num
            // 
            this.m_testTime_Num.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_testTime_Num.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_testTime_Num.BlinkDynamicsValue = false;
            this.m_testTime_Num.Bold = true;
            this.m_testTime_Num.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_testTime_Num.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_testTime_Num.DelayMouseInputPeriod = 0;
            this.m_testTime_Num.EnabledDynamicsValue = true;
            this.m_testTime_Num.FontSizePixels = 20;
            this.m_testTime_Num.Height = 35;
            this.m_testTime_Num.Left = 561;
            this.m_testTime_Num.MaxNumberOfCharacters = 3;
            this.m_testTime_Num.MaxValue = 5000D;
            this.m_testTime_Num.MinValue = 1D;
            this.m_testTime_Num.Name = "m_testTime_Num";
            this.m_testTime_Num.NumberOfDecimals = 0;
            this.m_testTime_Num.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_testTime_Num.ReadOnly = true;
            this.m_testTime_Num.ScreenOwnerName = "HomeScreen";
            this.m_testTime_Num.Top = 0;
            this.m_testTime_Num.ValidateValueOnInput = true;
            this.m_testTime_Num.Visible = false;
            this.m_testTime_Num.Width = 150;
            // 
            // m_AnalogNumeric
            // 
            this.m_AnalogNumeric.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_AnalogNumeric.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_AnalogNumeric.BlinkDynamicsValue = false;
            this.m_AnalogNumeric.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_AnalogNumeric.DelayMouseInputPeriod = 0;
            this.m_AnalogNumeric.EnabledDynamicsValue = true;
            this.m_AnalogNumeric.FontSizePixels = 20;
            this.m_AnalogNumeric.Height = 26;
            this.m_AnalogNumeric.Left = 5;
            this.m_AnalogNumeric.Name = "m_AnalogNumeric";
            this.m_AnalogNumeric.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_AnalogNumeric.ReadOnly = true;
            this.m_AnalogNumeric.ScreenOwnerName = "HomeScreen";
            this.m_AnalogNumeric.Top = 180;
            this.m_AnalogNumeric.Visible = false;
            this.m_AnalogNumeric.Width = 30;
            // 
            // m_AnalogNumeric1
            // 
            this.m_AnalogNumeric1.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_AnalogNumeric1.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_AnalogNumeric1.BlinkDynamicsValue = false;
            this.m_AnalogNumeric1.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric1.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_AnalogNumeric1.DelayMouseInputPeriod = 0;
            this.m_AnalogNumeric1.EnabledDynamicsValue = true;
            this.m_AnalogNumeric1.FontSizePixels = 20;
            this.m_AnalogNumeric1.Height = 26;
            this.m_AnalogNumeric1.Left = 0;
            this.m_AnalogNumeric1.Name = "m_AnalogNumeric1";
            this.m_AnalogNumeric1.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_AnalogNumeric1.ReadOnly = true;
            this.m_AnalogNumeric1.ScreenOwnerName = "HomeScreen";
            this.m_AnalogNumeric1.Top = 183;
            this.m_AnalogNumeric1.Visible = false;
            this.m_AnalogNumeric1.Width = 15;
            // 
            // m_Group1
            // 
            this.m_Group1.BlinkDynamicsValue = false;
            this.m_Group1.Components.Add(this.m_prewashWaterTime_Num);
            this.m_Group1.Components.Add(this.m_prewashRestTime_Num);
            this.m_Group1.Components.Add(this.m_dryingAirTime_Num);
            this.m_Group1.Components.Add(this.m_dryingRestTime_Num);
            this.m_Group1.Components.Add(this.m_cleaningWaterTime_Num);
            this.m_Group1.Components.Add(this.m_cleaningPressTime_Num);
            this.m_Group1.Components.Add(this.m_cleaningRestTime_Num);
            this.m_Group1.Components.Add(this.m_testTime_Num);
            this.m_Group1.Components.Add(this.m_AnalogNumeric);
            this.m_Group1.Components.Add(this.m_AnalogNumeric1);
            this.m_Group1.DelayMouseInputPeriod = 0;
            this.m_Group1.EnabledDynamicsValue = true;
            this.m_Group1.Height = 414;
            this.m_Group1.Left = 45;
            this.m_Group1.Name = "m_Group1";
            this.m_Group1.ParentGroup = null;
            this.m_Group1.ScreenOwnerName = "HomeScreen";
            this.m_Group1.Top = 17;
            this.m_Group1.VisibleDynamicsValue = true;
            this.m_Group1.Width = 711;
            // 
            // m_AnalogNumeric2
            // 
            this.m_AnalogNumeric2.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_AnalogNumeric2.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_AnalogNumeric2.BlinkDynamicsValue = false;
            this.m_AnalogNumeric2.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric2.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_AnalogNumeric2.DelayMouseInputPeriod = 0;
            this.m_AnalogNumeric2.EnabledDynamicsValue = true;
            this.m_AnalogNumeric2.FontSizePixels = 20;
            this.m_AnalogNumeric2.Height = 30;
            this.m_AnalogNumeric2.Left = 65;
            this.m_AnalogNumeric2.Name = "m_AnalogNumeric2";
            this.m_AnalogNumeric2.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_AnalogNumeric2.ReadOnly = true;
            this.m_AnalogNumeric2.ScreenOwnerName = "HomeScreen";
            this.m_AnalogNumeric2.Top = 91;
            this.m_AnalogNumeric2.Visible = false;
            this.m_AnalogNumeric2.Width = 100;
            // 
            // m_an_WaterLevel
            // 
            this.m_an_WaterLevel.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_an_WaterLevel.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_an_WaterLevel.BlinkDynamicsValue = false;
            this.m_an_WaterLevel.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_an_WaterLevel.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_an_WaterLevel.DelayMouseInputPeriod = 0;
            this.m_an_WaterLevel.EnabledDynamicsValue = true;
            this.m_an_WaterLevel.FontSizePixels = 20;
            this.m_an_WaterLevel.Height = 30;
            this.m_an_WaterLevel.Left = 724;
            this.m_an_WaterLevel.Name = "m_an_WaterLevel";
            this.m_an_WaterLevel.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_an_WaterLevel.ReadOnly = true;
            this.m_an_WaterLevel.ScreenOwnerName = "HomeScreen";
            this.m_an_WaterLevel.Top = 28;
            this.m_an_WaterLevel.Visible = false;
            this.m_an_WaterLevel.Width = 100;
            // 
            // m_AnalogNumeric3
            // 
            this.m_AnalogNumeric3.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_AnalogNumeric3.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_AnalogNumeric3.BlinkDynamicsValue = false;
            this.m_AnalogNumeric3.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric3.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_AnalogNumeric3.DelayMouseInputPeriod = 0;
            this.m_AnalogNumeric3.EnabledDynamicsValue = true;
            this.m_AnalogNumeric3.FontSizePixels = 20;
            this.m_AnalogNumeric3.Height = 30;
            this.m_AnalogNumeric3.Left = 690;
            this.m_AnalogNumeric3.Name = "m_AnalogNumeric3";
            this.m_AnalogNumeric3.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_AnalogNumeric3.ReadOnly = true;
            this.m_AnalogNumeric3.ScreenOwnerName = "HomeScreen";
            this.m_AnalogNumeric3.Top = 22;
            this.m_AnalogNumeric3.Visible = false;
            this.m_AnalogNumeric3.Width = 100;
            // 
            // m_AnalogNumeric4
            // 
            this.m_AnalogNumeric4.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_AnalogNumeric4.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_AnalogNumeric4.BlinkDynamicsValue = false;
            this.m_AnalogNumeric4.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric4.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_AnalogNumeric4.DelayMouseInputPeriod = 0;
            this.m_AnalogNumeric4.EnabledDynamicsValue = true;
            this.m_AnalogNumeric4.FontSizePixels = 20;
            this.m_AnalogNumeric4.Height = 30;
            this.m_AnalogNumeric4.Left = 690;
            this.m_AnalogNumeric4.Name = "m_AnalogNumeric4";
            this.m_AnalogNumeric4.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_AnalogNumeric4.ReadOnly = true;
            this.m_AnalogNumeric4.ScreenOwnerName = "HomeScreen";
            this.m_AnalogNumeric4.Top = 22;
            this.m_AnalogNumeric4.Visible = false;
            this.m_AnalogNumeric4.Width = 100;
            // 
            // m_Picture4
            // 
            this.m_Picture4.BlinkDynamicsValue = false;
            this.m_Picture4.DelayMouseInputPeriod = 0;
            this.m_Picture4.EnabledDynamicsValue = true;
            this.m_Picture4.Height = 120;
            this.m_Picture4.Left = 410;
            this.m_Picture4.Name = "m_Picture4";
            this.m_Picture4.ScreenOwnerName = "HomeScreen";
            this.m_Picture4.Stretch = true;
            this.m_Picture4.SymbolName = "italy-flag-3d-round-icon-256";
            this.m_Picture4.Top = 100;
            this.m_Picture4.VisibleDynamicsValue = true;
            this.m_Picture4.Width = 120;
            // 
            // m_Picture5
            // 
            this.m_Picture5.BlinkDynamicsValue = false;
            this.m_Picture5.DelayMouseInputPeriod = 0;
            this.m_Picture5.EnabledDynamicsValue = true;
            this.m_Picture5.Height = 120;
            this.m_Picture5.Left = 270;
            this.m_Picture5.Name = "m_Picture5";
            this.m_Picture5.ScreenOwnerName = "HomeScreen";
            this.m_Picture5.Stretch = true;
            this.m_Picture5.SymbolName = "portugal-flag-3d-round-icon-256";
            this.m_Picture5.Top = 100;
            this.m_Picture5.VisibleDynamicsValue = true;
            this.m_Picture5.Width = 120;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "HomeScreen";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_HomeScreen = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_HomeScreen) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_Logo);
            this.DrawingPrimitives.Add(this.m_KSPFull);
            this.DrawingPrimitives.Add(this.m_HSEnglishFlag);
            this.DrawingPrimitives.Add(this.m_Date_Time);
            this.DrawingPrimitives.Add(this.m_Picture1);
            this.DrawingPrimitives.Add(this.m_prewashWaterTime_Num);
            this.DrawingPrimitives.Add(this.m_prewashRestTime_Num);
            this.DrawingPrimitives.Add(this.m_dryingAirTime_Num);
            this.DrawingPrimitives.Add(this.m_dryingRestTime_Num);
            this.DrawingPrimitives.Add(this.m_cleaningWaterTime_Num);
            this.DrawingPrimitives.Add(this.m_cleaningPressTime_Num);
            this.DrawingPrimitives.Add(this.m_cleaningRestTime_Num);
            this.DrawingPrimitives.Add(this.m_testTime_Num);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric1);
            this.DrawingPrimitives.Add(this.m_Group1);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric2);
            this.DrawingPrimitives.Add(this.m_an_WaterLevel);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric3);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric4);
            this.DrawingPrimitives.Add(this.m_Picture4);
            this.DrawingPrimitives.Add(this.m_Picture5);
            ((System.ComponentModel.ISupportInitialize)(this.m_Logo)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_KSPFull)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_HSEnglishFlag)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Date_Time)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_prewashWaterTime_Num)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_prewashRestTime_Num)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_dryingAirTime_Num)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_dryingRestTime_Num)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_cleaningWaterTime_Num)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_cleaningPressTime_Num)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_cleaningRestTime_Num)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_testTime_Num)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Group1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_an_WaterLevel)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture5)).EndInit();
        }
        
        private void m_HSEnglishFlag_Action_MouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_HSEnglishFlag", "MouseDown", "Show Screen", "Automatic_Screen", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.Automatic_Screen.Show();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_HSEnglishFlag", "MouseDown", "Set Language", "MultipleLanguages", "");
            Neo.ApplicationFramework.Generated.Globals.MultipleLanguages.SetLanguage("Default");
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_HSEnglishFlag", "MouseDown", "Set Analog", "Tags.SystemLanguage", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.SystemLanguage.SetAnalog(1);
        }
        
        private void m_Date_Time_Action_MouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Date_Time", "MouseDown", "Set Date and Time", "", "");
            Core.Api.Service.ServiceContainerCF.GetService<Neo.ApplicationFramework.Interfaces.IDateTimeEditService>().ShowChangeDateTimeDialog();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Date_Time", "MouseDown", "Set Time Zone, Region and Daylight Saving", "", "");
            Core.Api.Service.ServiceContainerCF.GetService<Neo.ApplicationFramework.Interfaces.IDateTimeEditService>().ShowChangeTimeZoneDialog();
        }
        
        private void m_Picture1_Action_MouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Picture1", "MouseDown", "Show Screen", "Automatic_Screen", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.Automatic_Screen.Show();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Picture1", "MouseDown", "Set Language", "MultipleLanguages", "");
            Neo.ApplicationFramework.Generated.Globals.MultipleLanguages.SetLanguage("Spanish (Spain, International Sort)");
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Picture1", "MouseDown", "Set Analog", "Tags.SystemLanguage", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.SystemLanguage.SetAnalog(2);
        }
        
        private void m_Picture4_Action_MouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Picture4", "MouseDown", "Show Screen", "Automatic_Screen", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.Automatic_Screen.Show();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Picture4", "MouseDown", "Set Language", "MultipleLanguages", "");
            Neo.ApplicationFramework.Generated.Globals.MultipleLanguages.SetLanguage("Italian (Italy)");
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Picture4", "MouseDown", "Set Analog", "Tags.SystemLanguage", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.SystemLanguage.SetAnalog(4);
        }
        
        private void m_Picture5_Action_MouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Picture5", "MouseDown", "Show Screen", "Automatic_Screen", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.Automatic_Screen.Show();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Picture5", "MouseDown", "Set Language", "MultipleLanguages", "");
            Neo.ApplicationFramework.Generated.Globals.MultipleLanguages.SetLanguage("Portuguese (Portugal)");
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Picture5", "MouseDown", "Set Analog", "Tags.SystemLanguage", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.SystemLanguage.SetAnalog(3);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(HomeScreen));
            this.m_prewashWaterTime_Num.Suffix = resources.GetText("HomeScreen.prewashWaterTime_Num.Suffix", " sec");
            this.m_prewashRestTime_Num.Suffix = resources.GetText("HomeScreen.prewashRestTime_Num.Suffix", " sec");
            this.m_dryingAirTime_Num.Suffix = resources.GetText("HomeScreen.dryingAirTime_Num.Suffix", " sec");
            this.m_dryingRestTime_Num.Suffix = resources.GetText("HomeScreen.dryingRestTime_Num.Suffix", " sec");
            this.m_cleaningWaterTime_Num.Suffix = resources.GetText("HomeScreen.cleaningWaterTime_Num.Suffix", " sec");
            this.m_cleaningPressTime_Num.Suffix = resources.GetText("HomeScreen.cleaningPressTime_Num.Suffix", " sec");
            this.m_cleaningRestTime_Num.Suffix = resources.GetText("HomeScreen.cleaningRestTime_Num.Suffix", " sec");
            this.m_testTime_Num.Suffix = resources.GetText("HomeScreen.testTime_Num.Suffix", " sec.");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage() {
            this.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_HomeScreen) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.prewashWaterTime"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_prewashWaterTime_Num.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.prewashRestTime"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_prewashRestTime_Num.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding3 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.dryingAirTime"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_dryingAirTime_Num.DataBindings.Add(dynamicBinding3);
            this.m_DynamicBindings.Add(dynamicBinding3);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding4 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.dryingRestTime"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_dryingRestTime_Num.DataBindings.Add(dynamicBinding4);
            this.m_DynamicBindings.Add(dynamicBinding4);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding5 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.cleaningWaterTime"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_cleaningWaterTime_Num.DataBindings.Add(dynamicBinding5);
            this.m_DynamicBindings.Add(dynamicBinding5);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding6 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.cleaningPressTime"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_cleaningPressTime_Num.DataBindings.Add(dynamicBinding6);
            this.m_DynamicBindings.Add(dynamicBinding6);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding7 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.cleaningRestTime"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_cleaningRestTime_Num.DataBindings.Add(dynamicBinding7);
            this.m_DynamicBindings.Add(dynamicBinding7);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding8 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.TestTime"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_testTime_Num.DataBindings.Add(dynamicBinding8);
            this.m_DynamicBindings.Add(dynamicBinding8);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding9 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Man_Pre_Wash_Cycle"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric.DataBindings.Add(dynamicBinding9);
            this.m_DynamicBindings.Add(dynamicBinding9);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding10 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.ManWash_Dry_Cycle"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric1.DataBindings.Add(dynamicBinding10);
            this.m_DynamicBindings.Add(dynamicBinding10);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding11 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.WaterLevelSwitch"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric2.DataBindings.Add(dynamicBinding11);
            this.m_DynamicBindings.Add(dynamicBinding11);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding12 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.WaterLevelSwitch"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_an_WaterLevel.DataBindings.Add(dynamicBinding12);
            this.m_DynamicBindings.Add(dynamicBinding12);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding13 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.MagneticDoorSwitch"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric3.DataBindings.Add(dynamicBinding13);
            this.m_DynamicBindings.Add(dynamicBinding13);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding14 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Green_Light"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric4.DataBindings.Add(dynamicBinding14);
            this.m_DynamicBindings.Add(dynamicBinding14);
        }
    }
}
