//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class Settings_Screen : Neo.ApplicationFramework.Controls.Controls.Form, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage {
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture4;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle1;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric4;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text4;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text3;
        
        private Neo.ApplicationFramework.Controls.Controls.GroupCF m_Bot;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Pressure_Valve;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Blower_Test;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Washing_Pump_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Washing_Gun_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Admin_Page_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Home_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.DigitalClockCF m_DigitalClock3;
        
        private Neo.ApplicationFramework.Controls.Controls.DigitalClockCF m_DigitalClock4;
        
        private Neo.ApplicationFramework.Controls.Controls.GroupCF m_DateClock;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Calibration_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric1;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric2;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric3;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text2;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric5;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle2;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text1;
        
        private bool m_Initialized_Settings_Screen;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf1;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf2;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf3;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf4;
        
        public Settings_Screen() {
            this.InitializeComponent();
            this.Calibration_Button.Click += new System.EventHandler(this.Calibration_Button_Click);
            this.AnalogNumeric3.ValueChanged += new System.EventHandler<Core.Api.DataSource.ValueChangedEventArgs>(this.AnalogNumeric3_ValueChanged);
            this.Adapter.Closed += new System.EventHandler(this.Settings_Screen_Closed);
            this.m_Pressure_Valve.Click += new System.EventHandler(this.m_Pressure_Valve_Action_Click);
            this.m_Blower_Test.Click += new System.EventHandler(this.m_Blower_Test_Action_Click);
            this.m_Washing_Pump_Button.Click += new System.EventHandler(this.m_Washing_Pump_Button_Action_Click);
            this.m_Washing_Gun_Button.Click += new System.EventHandler(this.m_Washing_Gun_Button_Action_Click);
            this.m_Admin_Page_Button.Click += new System.EventHandler(this.m_Admin_Page_Button_Action_Click);
            this.m_Home_Button.Click += new System.EventHandler(this.m_Home_Button_Action_Click);
            this.m_Button.Click += new System.EventHandler(this.m_Button_Action_Click);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.GroupCFAdapter Bot {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.GroupCFAdapter>(this.m_Bot);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Pressure_Valve {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Pressure_Valve);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Blower_Test {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Blower_Test);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Washing_Pump_Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Washing_Pump_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Washing_Gun_Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Washing_Gun_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Admin_Page_Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Admin_Page_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Home_Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Home_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.GroupCFAdapter DateClock {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.GroupCFAdapter>(this.m_DateClock);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter DigitalClock3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_DigitalClock3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter DigitalClock4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_DigitalClock4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Calibration_Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Calibration_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text1);
            }
        }
        
        private void InitializeComponent() {
            this.brushdynamicsconvertercf4 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            this.brushdynamicsconvertercf3 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            this.brushdynamicsconvertercf2 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            this.brushdynamicsconvertercf1 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval1 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval2 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval3 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval4 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval5 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval6 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval7 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval8 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper5 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper6 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper7 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper8 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            this.m_Picture4 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Rectangle1 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_AnalogNumeric4 = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_Text4 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_AnalogNumeric = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_Text3 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Bot = new Neo.ApplicationFramework.Controls.Controls.GroupCF();
            this.m_Pressure_Valve = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Blower_Test = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Washing_Pump_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Washing_Gun_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Admin_Page_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Home_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_DigitalClock3 = new Neo.ApplicationFramework.Controls.Controls.DigitalClockCF();
            this.m_DigitalClock4 = new Neo.ApplicationFramework.Controls.Controls.DigitalClockCF();
            this.m_DateClock = new Neo.ApplicationFramework.Controls.Controls.GroupCF();
            this.m_Rectangle = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Calibration_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_AnalogNumeric1 = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_AnalogNumeric2 = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_AnalogNumeric3 = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Text2 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_AnalogNumeric5 = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_Rectangle2 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text1 = new Neo.ApplicationFramework.Controls.Controls.Label();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Bot)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Pressure_Valve)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Blower_Test)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Washing_Pump_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Washing_Gun_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Admin_Page_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Home_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_DigitalClock3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_DigitalClock4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_DateClock)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Calibration_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).BeginInit();
            this.SuspendLayout();
            // 
            // Settings_Screen
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(130)))), ((int)(((byte)(31))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.ThreeDBorder;
            this.ControlBox = false;
            // 
            // m_Picture4
            // 
            this.m_Picture4.BlinkDynamicsValue = false;
            this.m_Picture4.DelayMouseInputPeriod = 0;
            this.m_Picture4.EnabledDynamicsValue = true;
            this.m_Picture4.Height = 482;
            this.m_Picture4.Left = 464;
            this.m_Picture4.Name = "m_Picture4";
            this.m_Picture4.ScreenOwnerName = "Settings_Screen";
            this.m_Picture4.Stretch = true;
            this.m_Picture4.SymbolName = "logobeyaz";
            this.m_Picture4.Top = 17;
            this.m_Picture4.VisibleDynamicsValue = true;
            this.m_Picture4.Width = 475;
            // 
            // m_Rectangle1
            // 
            this.m_Rectangle1.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle1.BlinkDynamicsValue = false;
            this.m_Rectangle1.DelayMouseInputPeriod = 0;
            this.m_Rectangle1.EnabledDynamicsValue = true;
            this.m_Rectangle1.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Rectangle1.Height = 70;
            this.m_Rectangle1.Left = 0;
            this.m_Rectangle1.Name = "m_Rectangle1";
            this.m_Rectangle1.ScreenOwnerName = "Settings_Screen";
            this.m_Rectangle1.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(49)))), ((int)(((byte)(146))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle1.StrokeThickness = 5;
            this.m_Rectangle1.Top = 0;
            this.m_Rectangle1.VisibleDynamicsValue = true;
            this.m_Rectangle1.Width = 750;
            // 
            // m_AnalogNumeric4
            // 
            this.m_AnalogNumeric4.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_AnalogNumeric4.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_AnalogNumeric4.BlinkDynamicsValue = false;
            this.m_AnalogNumeric4.Bold = true;
            this.m_AnalogNumeric4.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(49)))), ((int)(((byte)(146))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric4.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_AnalogNumeric4.DelayMouseInputPeriod = 0;
            this.m_AnalogNumeric4.DisplayFormat = Neo.ApplicationFramework.Interfaces.AnalogNumericDisplayFormat.String;
            this.m_AnalogNumeric4.EnabledDynamicsValue = true;
            this.m_AnalogNumeric4.FontSizePixels = 20;
            this.m_AnalogNumeric4.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(49)))), ((int)(((byte)(146)))));
            this.m_AnalogNumeric4.Height = 42;
            this.m_AnalogNumeric4.Left = 214;
            this.m_AnalogNumeric4.MaxNumberOfCharacters = 20;
            this.m_AnalogNumeric4.Name = "m_AnalogNumeric4";
            this.m_AnalogNumeric4.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_AnalogNumeric4.ScreenOwnerName = "Settings_Screen";
            this.m_AnalogNumeric4.Top = 14;
            this.m_AnalogNumeric4.VisibleDynamicsValue = true;
            this.m_AnalogNumeric4.Width = 199;
            // 
            // m_Text4
            // 
            this.m_Text4.BlinkDynamicsValue = false;
            this.m_Text4.Bold = true;
            this.m_Text4.DelayMouseInputPeriod = 0;
            this.m_Text4.EnabledDynamicsValue = true;
            this.m_Text4.FontSizePixels = 18;
            this.m_Text4.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(49)))), ((int)(((byte)(146)))));
            this.m_Text4.Height = 21;
            this.m_Text4.Left = 7;
            this.m_Text4.Name = "m_Text4";
            this.m_Text4.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(4.5D, 0D, 4.5D, 1D);
            this.m_Text4.ScreenOwnerName = "Settings_Screen";
            this.m_Text4.Top = 20;
            this.m_Text4.VisibleDynamicsValue = true;
            this.m_Text4.Width = 89;
            // 
            // m_AnalogNumeric
            // 
            this.m_AnalogNumeric.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_AnalogNumeric.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_AnalogNumeric.BlinkDynamicsValue = false;
            this.m_AnalogNumeric.Bold = true;
            this.m_AnalogNumeric.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_AnalogNumeric.DelayMouseInputPeriod = 0;
            this.m_AnalogNumeric.EnabledDynamicsValue = true;
            this.m_AnalogNumeric.FontSizePixels = 18;
            this.m_AnalogNumeric.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(49)))), ((int)(((byte)(146)))));
            this.m_AnalogNumeric.Height = 39;
            this.m_AnalogNumeric.Left = 581;
            this.m_AnalogNumeric.Name = "m_AnalogNumeric";
            this.m_AnalogNumeric.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_AnalogNumeric.ReadOnly = true;
            this.m_AnalogNumeric.ScreenOwnerName = "Settings_Screen";
            this.m_AnalogNumeric.Top = 14;
            this.m_AnalogNumeric.Transparent = true;
            this.m_AnalogNumeric.VisibleDynamicsValue = true;
            this.m_AnalogNumeric.Width = 156;
            // 
            // m_Text3
            // 
            this.m_Text3.BlinkDynamicsValue = false;
            this.m_Text3.Bold = true;
            this.m_Text3.DelayMouseInputPeriod = 0;
            this.m_Text3.EnabledDynamicsValue = true;
            this.m_Text3.FontSizePixels = 18;
            this.m_Text3.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(49)))), ((int)(((byte)(146)))));
            this.m_Text3.Height = 21;
            this.m_Text3.Left = 431;
            this.m_Text3.Name = "m_Text3";
            this.m_Text3.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(4.5D, 0D, 4.5D, 1D);
            this.m_Text3.ScreenOwnerName = "Settings_Screen";
            this.m_Text3.Top = 20;
            this.m_Text3.VisibleDynamicsValue = true;
            this.m_Text3.Width = 92;
            // 
            // m_Bot
            // 
            this.m_Bot.BlinkDynamicsValue = false;
            this.m_Bot.Components.Add(this.m_Rectangle1);
            this.m_Bot.Components.Add(this.m_AnalogNumeric4);
            this.m_Bot.Components.Add(this.m_Text4);
            this.m_Bot.Components.Add(this.m_AnalogNumeric);
            this.m_Bot.Components.Add(this.m_Text3);
            this.m_Bot.DelayMouseInputPeriod = 0;
            this.m_Bot.EnabledDynamicsValue = true;
            this.m_Bot.Height = 70;
            this.m_Bot.Left = 25;
            this.m_Bot.Name = "m_Bot";
            this.m_Bot.ParentGroup = null;
            this.m_Bot.ScreenOwnerName = "Settings_Screen";
            this.m_Bot.Top = 394;
            this.m_Bot.VisibleDynamicsValue = true;
            this.m_Bot.Width = 750;
            // 
            // m_Pressure_Valve
            // 
            this.m_Pressure_Valve.BlinkDynamicsValue = false;
            this.m_Pressure_Valve.Bold = true;
            this.m_Pressure_Valve.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Pressure_Valve.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            brushdynamicsconvertercf1.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.White, System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            brushcfinterval1.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(28)))), ((int)(((byte)(36))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval2.End = 1D;
            brushcfinterval2.Start = 1D;
            brushcfinterval2.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(177)))), ((int)(((byte)(76))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushdynamicsconvertercf1.BrushIntervalMapper.Intervals.Add(brushcfinterval1);
            brushdynamicsconvertercf1.BrushIntervalMapper.Intervals.Add(brushcfinterval2);
            this.m_Pressure_Valve.DelayMouseInputPeriod = 0;
            this.m_Pressure_Valve.EnabledDynamicsValue = true;
            this.m_Pressure_Valve.FontSizePixels = 18;
            this.m_Pressure_Valve.ForceTransparency = true;
            this.m_Pressure_Valve.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Pressure_Valve.Height = 75;
            this.m_Pressure_Valve.ImageHorizontalAlignment = "Right";
            this.m_Pressure_Valve.IndicatorMargin = null;
            this.m_Pressure_Valve.Left = 21;
            this.m_Pressure_Valve.MultiLine = true;
            this.m_Pressure_Valve.Name = "m_Pressure_Valve";
            this.m_Pressure_Valve.RequiresTransparency = true;
            this.m_Pressure_Valve.ScreenOwnerName = "Settings_Screen";
            this.m_Pressure_Valve.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_Pressure_Valve.TextHeight = 44;
            this.m_Pressure_Valve.TextValue = 0D;
            this.m_Pressure_Valve.TextWidth = 188;
            this.m_Pressure_Valve.Top = 90;
            this.m_Pressure_Valve.Value = 0D;
            this.m_Pressure_Valve.VisibleDynamicsValue = true;
            this.m_Pressure_Valve.VisualPropertiesHashCode = -856425045;
            this.m_Pressure_Valve.Width = 200;
            this.m_Pressure_Valve.WordWrap = true;
            // 
            // m_Blower_Test
            // 
            this.m_Blower_Test.BlinkDynamicsValue = false;
            this.m_Blower_Test.Bold = true;
            this.m_Blower_Test.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Blower_Test.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            brushdynamicsconvertercf2.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.White, System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            brushcfinterval3.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(28)))), ((int)(((byte)(36))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval4.End = 1D;
            brushcfinterval4.Start = 1D;
            brushcfinterval4.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(177)))), ((int)(((byte)(76))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushdynamicsconvertercf2.BrushIntervalMapper.Intervals.Add(brushcfinterval3);
            brushdynamicsconvertercf2.BrushIntervalMapper.Intervals.Add(brushcfinterval4);
            this.m_Blower_Test.DelayMouseInputPeriod = 0;
            this.m_Blower_Test.EnabledDynamicsValue = true;
            this.m_Blower_Test.FontSizePixels = 18;
            this.m_Blower_Test.ForceTransparency = true;
            this.m_Blower_Test.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Blower_Test.Height = 75;
            this.m_Blower_Test.IndicatorMargin = null;
            this.m_Blower_Test.Left = 244;
            this.m_Blower_Test.MultiLine = true;
            this.m_Blower_Test.Name = "m_Blower_Test";
            this.m_Blower_Test.RequiresTransparency = true;
            this.m_Blower_Test.ScreenOwnerName = "Settings_Screen";
            this.m_Blower_Test.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_Blower_Test.TextHeight = 44;
            this.m_Blower_Test.TextValue = 0D;
            this.m_Blower_Test.TextWidth = 188;
            this.m_Blower_Test.Top = 90;
            this.m_Blower_Test.Value = 0D;
            this.m_Blower_Test.VisibleDynamicsValue = true;
            this.m_Blower_Test.VisualPropertiesHashCode = 1077183945;
            this.m_Blower_Test.Width = 200;
            this.m_Blower_Test.WordWrap = true;
            // 
            // m_Washing_Pump_Button
            // 
            this.m_Washing_Pump_Button.BlinkDynamicsValue = false;
            this.m_Washing_Pump_Button.Bold = true;
            this.m_Washing_Pump_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Washing_Pump_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            brushdynamicsconvertercf3.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.White, System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            brushcfinterval5.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(28)))), ((int)(((byte)(36))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval6.End = 1D;
            brushcfinterval6.Start = 1D;
            brushcfinterval6.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(177)))), ((int)(((byte)(76))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushdynamicsconvertercf3.BrushIntervalMapper.Intervals.Add(brushcfinterval5);
            brushdynamicsconvertercf3.BrushIntervalMapper.Intervals.Add(brushcfinterval6);
            this.m_Washing_Pump_Button.DelayMouseInputPeriod = 0;
            this.m_Washing_Pump_Button.EnabledDynamicsValue = true;
            this.m_Washing_Pump_Button.FontSizePixels = 18;
            this.m_Washing_Pump_Button.ForceTransparency = true;
            this.m_Washing_Pump_Button.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Washing_Pump_Button.Height = 75;
            this.m_Washing_Pump_Button.ImageVerticalAlignment = "Bottom";
            this.m_Washing_Pump_Button.IndicatorMargin = null;
            this.m_Washing_Pump_Button.Left = 21;
            this.m_Washing_Pump_Button.MultiLine = true;
            this.m_Washing_Pump_Button.Name = "m_Washing_Pump_Button";
            this.m_Washing_Pump_Button.RequiresTransparency = true;
            this.m_Washing_Pump_Button.ScreenOwnerName = "Settings_Screen";
            this.m_Washing_Pump_Button.SymbolIntervalMapper = symbolintervalmapper3;
            this.m_Washing_Pump_Button.TextHeight = 44;
            this.m_Washing_Pump_Button.TextValue = 0D;
            this.m_Washing_Pump_Button.TextWidth = 188;
            this.m_Washing_Pump_Button.Top = 181;
            this.m_Washing_Pump_Button.Value = 0D;
            this.m_Washing_Pump_Button.VisibleDynamicsValue = true;
            this.m_Washing_Pump_Button.VisualPropertiesHashCode = -595497116;
            this.m_Washing_Pump_Button.Width = 200;
            this.m_Washing_Pump_Button.WordWrap = true;
            // 
            // m_Washing_Gun_Button
            // 
            this.m_Washing_Gun_Button.BlinkDynamicsValue = false;
            this.m_Washing_Gun_Button.Bold = true;
            this.m_Washing_Gun_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Washing_Gun_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            brushdynamicsconvertercf4.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.White, System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            brushcfinterval7.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(28)))), ((int)(((byte)(36))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval8.End = 1D;
            brushcfinterval8.Start = 1D;
            brushcfinterval8.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(177)))), ((int)(((byte)(76))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushdynamicsconvertercf4.BrushIntervalMapper.Intervals.Add(brushcfinterval7);
            brushdynamicsconvertercf4.BrushIntervalMapper.Intervals.Add(brushcfinterval8);
            this.m_Washing_Gun_Button.DelayMouseInputPeriod = 0;
            this.m_Washing_Gun_Button.EnabledDynamicsValue = true;
            this.m_Washing_Gun_Button.FontSizePixels = 18;
            this.m_Washing_Gun_Button.ForceTransparency = true;
            this.m_Washing_Gun_Button.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Washing_Gun_Button.Height = 75;
            this.m_Washing_Gun_Button.ImageHorizontalAlignment = "Right";
            this.m_Washing_Gun_Button.ImageVerticalAlignment = "Bottom";
            this.m_Washing_Gun_Button.IndicatorMargin = null;
            this.m_Washing_Gun_Button.Left = 244;
            this.m_Washing_Gun_Button.MultiLine = true;
            this.m_Washing_Gun_Button.Name = "m_Washing_Gun_Button";
            this.m_Washing_Gun_Button.RequiresTransparency = true;
            this.m_Washing_Gun_Button.ScreenOwnerName = "Settings_Screen";
            this.m_Washing_Gun_Button.SymbolIntervalMapper = symbolintervalmapper4;
            this.m_Washing_Gun_Button.TextHeight = 44;
            this.m_Washing_Gun_Button.TextValue = 0D;
            this.m_Washing_Gun_Button.TextWidth = 188;
            this.m_Washing_Gun_Button.Top = 181;
            this.m_Washing_Gun_Button.Value = 0D;
            this.m_Washing_Gun_Button.VisibleDynamicsValue = true;
            this.m_Washing_Gun_Button.VisualPropertiesHashCode = 1414063821;
            this.m_Washing_Gun_Button.Width = 200;
            this.m_Washing_Gun_Button.WordWrap = true;
            // 
            // m_Admin_Page_Button
            // 
            this.m_Admin_Page_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Admin_Page_Button.BlinkDynamicsValue = false;
            this.m_Admin_Page_Button.Bold = true;
            this.m_Admin_Page_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Admin_Page_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 5D, 5D, 5D);
            this.m_Admin_Page_Button.DelayMouseInputPeriod = 0;
            this.m_Admin_Page_Button.EnabledDynamicsValue = true;
            this.m_Admin_Page_Button.FontSizePixels = 18;
            this.m_Admin_Page_Button.ForceTransparency = true;
            this.m_Admin_Page_Button.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Admin_Page_Button.Height = 100;
            this.m_Admin_Page_Button.IndicatorMargin = null;
            this.m_Admin_Page_Button.Left = 21;
            this.m_Admin_Page_Button.MultiLine = true;
            this.m_Admin_Page_Button.Name = "m_Admin_Page_Button";
            this.m_Admin_Page_Button.RequiresTransparency = true;
            this.m_Admin_Page_Button.ScreenOwnerName = "Settings_Screen";
            this.m_Admin_Page_Button.StyleName = "Chrome";
            this.m_Admin_Page_Button.SymbolIntervalMapper = symbolintervalmapper5;
            this.m_Admin_Page_Button.TextHeight = 44;
            this.m_Admin_Page_Button.TextValue = 0D;
            this.m_Admin_Page_Button.TextWidth = 194;
            this.m_Admin_Page_Button.Top = 274;
            this.m_Admin_Page_Button.Value = 0D;
            this.m_Admin_Page_Button.VisibleDynamicsValue = true;
            this.m_Admin_Page_Button.VisualPropertiesHashCode = -2048560093;
            this.m_Admin_Page_Button.Width = 200;
            this.m_Admin_Page_Button.WordWrap = true;
            // 
            // m_Home_Button
            // 
            this.m_Home_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(49)))), ((int)(((byte)(146))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Home_Button.BlinkDynamicsValue = false;
            this.m_Home_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Home_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 5D, 5D, 0D);
            this.m_Home_Button.DelayMouseInputPeriod = 0;
            this.m_Home_Button.EnabledDynamicsValue = true;
            this.m_Home_Button.FontSizePixels = 18;
            this.m_Home_Button.ForceTransparency = true;
            this.m_Home_Button.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Home_Button.Height = 58;
            this.m_Home_Button.ImageMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(10D, 10D, 10D, 10D);
            this.m_Home_Button.IndicatorMargin = null;
            this.m_Home_Button.Left = 10;
            this.m_Home_Button.Name = "m_Home_Button";
            this.m_Home_Button.RequiresTransparency = true;
            this.m_Home_Button.ScreenOwnerName = "Settings_Screen";
            this.m_Home_Button.StyleName = "Vintage";
            this.m_Home_Button.SymbolHeight = 36;
            this.m_Home_Button.SymbolIntervalMapper = symbolintervalmapper6;
            this.m_Home_Button.SymbolName = "home (1)";
            this.m_Home_Button.SymbolWidth = 40;
            this.m_Home_Button.TextHeight = 22;
            this.m_Home_Button.TextValue = 0D;
            this.m_Home_Button.TextWidth = 91;
            this.m_Home_Button.Top = 7;
            this.m_Home_Button.Value = 0D;
            this.m_Home_Button.VisibleDynamicsValue = true;
            this.m_Home_Button.VisualPropertiesHashCode = 1775881799;
            this.m_Home_Button.Width = 97;
            // 
            // m_DigitalClock3
            // 
            this.m_DigitalClock3.BlinkDynamicsValue = false;
            this.m_DigitalClock3.Bold = true;
            this.m_DigitalClock3.DelayMouseInputPeriod = 0;
            this.m_DigitalClock3.DisplayFormat = Neo.ApplicationFramework.Interfaces.DateTimeDisplayFormat.Date;
            this.m_DigitalClock3.EnabledDynamicsValue = true;
            this.m_DigitalClock3.FontSizePixels = 18;
            this.m_DigitalClock3.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_DigitalClock3.Height = 29;
            this.m_DigitalClock3.Left = 0;
            this.m_DigitalClock3.Name = "m_DigitalClock3";
            this.m_DigitalClock3.ScreenOwnerName = "Settings_Screen";
            this.m_DigitalClock3.ShowDayOfWeek = false;
            this.m_DigitalClock3.ShowSeconds = true;
            this.m_DigitalClock3.Text = "7.10.2019";
            this.m_DigitalClock3.Top = 0;
            this.m_DigitalClock3.VisibleDynamicsValue = true;
            this.m_DigitalClock3.Width = 166;
            // 
            // m_DigitalClock4
            // 
            this.m_DigitalClock4.BlinkDynamicsValue = false;
            this.m_DigitalClock4.Bold = true;
            this.m_DigitalClock4.DelayMouseInputPeriod = 0;
            this.m_DigitalClock4.DisplayFormat = Neo.ApplicationFramework.Interfaces.DateTimeDisplayFormat.Time;
            this.m_DigitalClock4.EnabledDynamicsValue = true;
            this.m_DigitalClock4.FontSizePixels = 18;
            this.m_DigitalClock4.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_DigitalClock4.Height = 29;
            this.m_DigitalClock4.Left = 6;
            this.m_DigitalClock4.Name = "m_DigitalClock4";
            this.m_DigitalClock4.ScreenOwnerName = "Settings_Screen";
            this.m_DigitalClock4.ShowDayOfWeek = false;
            this.m_DigitalClock4.ShowSeconds = true;
            this.m_DigitalClock4.Text = "18:09:19";
            this.m_DigitalClock4.Top = 20;
            this.m_DigitalClock4.VisibleDynamicsValue = true;
            this.m_DigitalClock4.Width = 143;
            // 
            // m_DateClock
            // 
            this.m_DateClock.BlinkDynamicsValue = false;
            this.m_DateClock.Components.Add(this.m_DigitalClock3);
            this.m_DateClock.Components.Add(this.m_DigitalClock4);
            this.m_DateClock.DelayMouseInputPeriod = 0;
            this.m_DateClock.EnabledDynamicsValue = true;
            this.m_DateClock.Height = 46;
            this.m_DateClock.Left = 643;
            this.m_DateClock.Name = "m_DateClock";
            this.m_DateClock.ParentGroup = null;
            this.m_DateClock.ScreenOwnerName = "Settings_Screen";
            this.m_DateClock.Top = 13;
            this.m_DateClock.VisibleDynamicsValue = true;
            this.m_DateClock.Width = 128;
            // 
            // m_Rectangle
            // 
            this.m_Rectangle.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(5, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_Rectangle.BlinkDynamicsValue = false;
            this.m_Rectangle.DelayMouseInputPeriod = 0;
            this.m_Rectangle.EnabledDynamicsValue = true;
            this.m_Rectangle.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Rectangle.Height = 420;
            this.m_Rectangle.Left = 0;
            this.m_Rectangle.Name = "m_Rectangle";
            this.m_Rectangle.ScreenOwnerName = "Settings_Screen";
            this.m_Rectangle.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle.StrokeThickness = 10;
            this.m_Rectangle.Top = 60;
            this.m_Rectangle.VisibleDynamicsValue = true;
            this.m_Rectangle.Width = 800;
            // 
            // m_Calibration_Button
            // 
            this.m_Calibration_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Calibration_Button.BlinkDynamicsValue = false;
            this.m_Calibration_Button.Bold = true;
            this.m_Calibration_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Calibration_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 5D, 5D, 5D);
            this.m_Calibration_Button.DelayMouseInputPeriod = 0;
            this.m_Calibration_Button.EnabledDynamicsValue = true;
            this.m_Calibration_Button.FontSizePixels = 18;
            this.m_Calibration_Button.ForceTransparency = true;
            this.m_Calibration_Button.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Calibration_Button.Height = 100;
            this.m_Calibration_Button.IndicatorMargin = null;
            this.m_Calibration_Button.Left = 244;
            this.m_Calibration_Button.MultiLine = true;
            this.m_Calibration_Button.Name = "m_Calibration_Button";
            this.m_Calibration_Button.RequiresTransparency = true;
            this.m_Calibration_Button.ScreenOwnerName = "Settings_Screen";
            this.m_Calibration_Button.StyleName = "Chrome";
            this.m_Calibration_Button.SymbolIntervalMapper = symbolintervalmapper7;
            this.m_Calibration_Button.TextHeight = 44;
            this.m_Calibration_Button.TextValue = 0D;
            this.m_Calibration_Button.TextWidth = 194;
            this.m_Calibration_Button.Top = 274;
            this.m_Calibration_Button.Value = 0D;
            this.m_Calibration_Button.VisibleDynamicsValue = true;
            this.m_Calibration_Button.VisualPropertiesHashCode = -2048560093;
            this.m_Calibration_Button.Width = 200;
            this.m_Calibration_Button.WordWrap = true;
            // 
            // m_AnalogNumeric1
            // 
            this.m_AnalogNumeric1.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_AnalogNumeric1.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_AnalogNumeric1.BlinkDynamicsValue = false;
            this.m_AnalogNumeric1.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric1.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_AnalogNumeric1.DelayMouseInputPeriod = 0;
            this.m_AnalogNumeric1.EnabledDynamicsValue = true;
            this.m_AnalogNumeric1.FontSizePixels = 20;
            this.m_AnalogNumeric1.Height = 30;
            this.m_AnalogNumeric1.Left = 550;
            this.m_AnalogNumeric1.Name = "m_AnalogNumeric1";
            this.m_AnalogNumeric1.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_AnalogNumeric1.ReadOnly = true;
            this.m_AnalogNumeric1.ScreenOwnerName = "Settings_Screen";
            this.m_AnalogNumeric1.Top = 145;
            this.m_AnalogNumeric1.Visible = false;
            this.m_AnalogNumeric1.Width = 100;
            // 
            // m_AnalogNumeric2
            // 
            this.m_AnalogNumeric2.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_AnalogNumeric2.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_AnalogNumeric2.BlinkDynamicsValue = false;
            this.m_AnalogNumeric2.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric2.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_AnalogNumeric2.DelayMouseInputPeriod = 0;
            this.m_AnalogNumeric2.EnabledDynamicsValue = true;
            this.m_AnalogNumeric2.FontSizePixels = 20;
            this.m_AnalogNumeric2.Height = 30;
            this.m_AnalogNumeric2.Left = 550;
            this.m_AnalogNumeric2.Name = "m_AnalogNumeric2";
            this.m_AnalogNumeric2.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_AnalogNumeric2.ReadOnly = true;
            this.m_AnalogNumeric2.ScreenOwnerName = "Settings_Screen";
            this.m_AnalogNumeric2.Top = 181;
            this.m_AnalogNumeric2.Visible = false;
            this.m_AnalogNumeric2.Width = 100;
            // 
            // m_AnalogNumeric3
            // 
            this.m_AnalogNumeric3.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_AnalogNumeric3.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_AnalogNumeric3.BlinkDynamicsValue = false;
            this.m_AnalogNumeric3.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric3.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_AnalogNumeric3.DelayMouseInputPeriod = 0;
            this.m_AnalogNumeric3.EnabledDynamicsValue = true;
            this.m_AnalogNumeric3.FontSizePixels = 20;
            this.m_AnalogNumeric3.Height = 4;
            this.m_AnalogNumeric3.Left = 602;
            this.m_AnalogNumeric3.Name = "m_AnalogNumeric3";
            this.m_AnalogNumeric3.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_AnalogNumeric3.ReadOnly = true;
            this.m_AnalogNumeric3.ScreenOwnerName = "Settings_Screen";
            this.m_AnalogNumeric3.Top = 34;
            this.m_AnalogNumeric3.Visible = false;
            this.m_AnalogNumeric3.Width = 4;
            // 
            // m_Button
            // 
            this.m_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BlinkDynamicsValue = false;
            this.m_Button.Bold = true;
            this.m_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 5D, 5D, 5D);
            this.m_Button.DelayMouseInputPeriod = 0;
            this.m_Button.EnabledDynamicsValue = true;
            this.m_Button.FontSizePixels = 18;
            this.m_Button.ForceTransparency = true;
            this.m_Button.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button.Height = 100;
            this.m_Button.IndicatorMargin = null;
            this.m_Button.Left = 464;
            this.m_Button.MultiLine = true;
            this.m_Button.Name = "m_Button";
            this.m_Button.RequiresTransparency = true;
            this.m_Button.ScreenOwnerName = "Settings_Screen";
            this.m_Button.StyleName = "Chrome";
            this.m_Button.SymbolIntervalMapper = symbolintervalmapper8;
            this.m_Button.TextHeight = 44;
            this.m_Button.TextValue = 0D;
            this.m_Button.TextWidth = 194;
            this.m_Button.Top = 274;
            this.m_Button.Value = 0D;
            this.m_Button.VisibleDynamicsValue = true;
            this.m_Button.VisualPropertiesHashCode = -2048560093;
            this.m_Button.Width = 200;
            this.m_Button.WordWrap = true;
            // 
            // m_Text2
            // 
            this.m_Text2.AutoSize = false;
            this.m_Text2.BlinkDynamicsValue = false;
            this.m_Text2.Bold = true;
            this.m_Text2.DelayMouseInputPeriod = 0;
            this.m_Text2.EnabledDynamicsValue = true;
            this.m_Text2.FontSizePixels = 22;
            this.m_Text2.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Text2.Height = 35;
            this.m_Text2.Left = 123;
            this.m_Text2.Name = "m_Text2";
            this.m_Text2.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5.5D, 0D, 5.5D, 1D);
            this.m_Text2.ScreenOwnerName = "Settings_Screen";
            this.m_Text2.TextVerticalAlignment = "Center";
            this.m_Text2.Top = 18;
            this.m_Text2.VisibleDynamicsValue = true;
            this.m_Text2.Width = 585;
            // 
            // m_AnalogNumeric5
            // 
            this.m_AnalogNumeric5.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_AnalogNumeric5.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_AnalogNumeric5.BlinkDynamicsValue = false;
            this.m_AnalogNumeric5.Bold = true;
            this.m_AnalogNumeric5.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric5.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_AnalogNumeric5.DelayMouseInputPeriod = 0;
            this.m_AnalogNumeric5.EnabledDynamicsValue = true;
            this.m_AnalogNumeric5.FontSizePixels = 20;
            this.m_AnalogNumeric5.Height = 35;
            this.m_AnalogNumeric5.Left = 485;
            this.m_AnalogNumeric5.MaxNumberOfCharacters = 2;
            this.m_AnalogNumeric5.MaxValue = 30D;
            this.m_AnalogNumeric5.MinValue = 1D;
            this.m_AnalogNumeric5.Name = "m_AnalogNumeric5";
            this.m_AnalogNumeric5.NumberOfDecimals = 0;
            this.m_AnalogNumeric5.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_AnalogNumeric5.ReadOnly = true;
            this.m_AnalogNumeric5.ScreenOwnerName = "Settings_Screen";
            this.m_AnalogNumeric5.Top = 18;
            this.m_AnalogNumeric5.VisibleDynamicsValue = true;
            this.m_AnalogNumeric5.Width = 150;
            // 
            // m_Rectangle2
            // 
            this.m_Rectangle2.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle2.BlinkDynamicsValue = false;
            this.m_Rectangle2.DelayMouseInputPeriod = 0;
            this.m_Rectangle2.EnabledDynamicsValue = true;
            this.m_Rectangle2.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(229)))), ((int)(((byte)(121)))), ((int)(((byte)(33))))), Neo.ApplicationFramework.Interfaces.FillDirection.Center);
            this.m_Rectangle2.Height = 480;
            this.m_Rectangle2.Left = 0;
            this.m_Rectangle2.Name = "m_Rectangle2";
            this.m_Rectangle2.ScreenOwnerName = "Settings_Screen";
            this.m_Rectangle2.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle2.StrokeThickness = 15;
            this.m_Rectangle2.Top = 0;
            this.m_Rectangle2.Visible = false;
            this.m_Rectangle2.Width = 800;
            // 
            // m_Text
            // 
            this.m_Text.AutoSize = false;
            this.m_Text.BlinkDynamicsValue = false;
            this.m_Text.Bold = true;
            this.m_Text.DelayMouseInputPeriod = 0;
            this.m_Text.EnabledDynamicsValue = true;
            this.m_Text.FontSizePixels = 20;
            this.m_Text.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(49)))), ((int)(((byte)(146)))));
            this.m_Text.Height = 480;
            this.m_Text.Left = 0;
            this.m_Text.Name = "m_Text";
            this.m_Text.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 0D, 5D, 1D);
            this.m_Text.ScreenOwnerName = "Settings_Screen";
            this.m_Text.TextHorizontalAlignment = "Center";
            this.m_Text.TextVerticalAlignment = "Center";
            this.m_Text.Top = 0;
            this.m_Text.Visible = false;
            this.m_Text.Width = 800;
            // 
            // m_Text1
            // 
            this.m_Text1.BlinkDynamicsValue = false;
            this.m_Text1.Bold = true;
            this.m_Text1.DelayMouseInputPeriod = 0;
            this.m_Text1.EnabledDynamicsValue = true;
            this.m_Text1.FontSizePixels = 20;
            this.m_Text1.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(49)))), ((int)(((byte)(146)))));
            this.m_Text1.Height = 21;
            this.m_Text1.Left = 143;
            this.m_Text1.Name = "m_Text1";
            this.m_Text1.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 0D, 5D, 1D);
            this.m_Text1.ScreenOwnerName = "Settings_Screen";
            this.m_Text1.TextHorizontalAlignment = "Center";
            this.m_Text1.TextVerticalAlignment = "Center";
            this.m_Text1.Top = 0;
            this.m_Text1.Visible = false;
            this.m_Text1.Width = 169;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "Settings_Screen";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_Settings_Screen = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_Settings_Screen) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_Picture4);
            this.DrawingPrimitives.Add(this.m_Rectangle1);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric4);
            this.DrawingPrimitives.Add(this.m_Text4);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric);
            this.DrawingPrimitives.Add(this.m_Text3);
            this.DrawingPrimitives.Add(this.m_Bot);
            this.DrawingPrimitives.Add(this.m_Pressure_Valve);
            this.DrawingPrimitives.Add(this.m_Blower_Test);
            this.DrawingPrimitives.Add(this.m_Washing_Pump_Button);
            this.DrawingPrimitives.Add(this.m_Washing_Gun_Button);
            this.DrawingPrimitives.Add(this.m_Admin_Page_Button);
            this.DrawingPrimitives.Add(this.m_Home_Button);
            this.DrawingPrimitives.Add(this.m_DigitalClock3);
            this.DrawingPrimitives.Add(this.m_DigitalClock4);
            this.DrawingPrimitives.Add(this.m_DateClock);
            this.DrawingPrimitives.Add(this.m_Rectangle);
            this.DrawingPrimitives.Add(this.m_Calibration_Button);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric1);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric2);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric3);
            this.DrawingPrimitives.Add(this.m_Button);
            this.DrawingPrimitives.Add(this.m_Text2);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric5);
            this.DrawingPrimitives.Add(this.m_Rectangle2);
            this.DrawingPrimitives.Add(this.m_Text);
            this.DrawingPrimitives.Add(this.m_Text1);
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Bot)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Pressure_Valve)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Blower_Test)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Washing_Pump_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Washing_Gun_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Admin_Page_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Home_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_DigitalClock3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_DigitalClock4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_DateClock)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Calibration_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).EndInit();
        }
        
        private void m_Pressure_Valve_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Pressure_Valve", "Click", "Toggle Tag", "Tags.Pressure_Valve", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Pressure_Valve.ToggleTag();
        }
        
        private void m_Blower_Test_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Blower_Test", "Click", "Toggle Tag", "Tags.Blower", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Blower.ToggleTag();
        }
        
        private void m_Washing_Pump_Button_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Washing_Pump_Button", "Click", "Toggle Tag", "Tags.Washing_Pump", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Washing_Pump.ToggleTag();
        }
        
        private void m_Washing_Gun_Button_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Washing_Gun_Button", "Click", "Toggle Tag", "Tags.Manual_Washing_Pump", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Manual_Washing_Pump.ToggleTag();
        }
        
        private void m_Admin_Page_Button_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Admin_Page_Button", "Click", "Show Screen", "LoginScreen", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.LoginScreen.Show();
        }
        
        private void m_Home_Button_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Home_Button", "Click", "Show Screen", "Automatic_Screen", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.Automatic_Screen.Show();
        }
        
        private void m_Button_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button", "Click", "Set Analog", "Tags.CleaningCounter", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.CleaningCounter.SetAnalog(0);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Settings_Screen));
            this.m_Pressure_Valve.Text = resources.GetText("Settings_Screen.Pressure_Valve.Text", "PRESSURE\r\nVALVE");
            this.m_Washing_Pump_Button.Text = resources.GetText("Settings_Screen.Washing_Pump_Button.Text", "WASHING \r\nPUMP");
            this.m_Washing_Gun_Button.Text = resources.GetText("Settings_Screen.Washing_Gun_Button.Text", "WASHING GUN\r\nPUMP");
            this.m_Blower_Test.Text = resources.GetText("Settings_Screen.Blower_Test.Text", "BLOWER\r\nTEST");
            this.m_Text4.Text = resources.GetText("Settings_Screen.Text4.Text", "COMPANY NAME");
            this.m_AnalogNumeric.Suffix = resources.GetText("Settings_Screen.AnalogNumeric.Suffix", " mbar");
            this.m_Text3.Text = resources.GetText("Settings_Screen.Text3.Text", "MAX. PRESSURE:");
            this.m_Admin_Page_Button.Text = resources.GetText("Settings_Screen.Admin_Page_Button.Text", "ADMIN\r\nPAGE");
            this.m_Calibration_Button.Text = resources.GetText("Settings_Screen.Calibration_Button.Text", "PRESSURE\r\nCALIBRATION");
            this.m_Text.Text = resources.GetText("Settings_Screen.Text.Text", "Wait for Calibration to Complete!");
            this.m_Text1.Text = resources.GetText("Settings_Screen.Text1.Text", "Wait for Calibration to Complete!");
            this.m_Button.Text = resources.GetText("Settings_Screen.Button.Text", "RESET\r\nCOUNTER");
            this.m_Text2.Text = resources.GetText("Settings_Screen.Text2.Text", "Filter Changing Counter");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage() {
            this.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_Settings_Screen) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Company_Name"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric4.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Max_Pressure"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding3 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Pressure_Valve"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Pressure_Valve.DataBindings.Add(dynamicBinding3);
            this.m_DynamicBindings.Add(dynamicBinding3);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding4 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Background", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Pressure_Valve"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf1);
            this.m_Pressure_Valve.DataBindings.Add(dynamicBinding4);
            this.m_DynamicBindings.Add(dynamicBinding4);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding5 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Blower"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Blower_Test.DataBindings.Add(dynamicBinding5);
            this.m_DynamicBindings.Add(dynamicBinding5);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding6 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Background", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Blower"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf2);
            this.m_Blower_Test.DataBindings.Add(dynamicBinding6);
            this.m_DynamicBindings.Add(dynamicBinding6);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding7 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Washing_Pump"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Washing_Pump_Button.DataBindings.Add(dynamicBinding7);
            this.m_DynamicBindings.Add(dynamicBinding7);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding8 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Background", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Washing_Pump"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf3);
            this.m_Washing_Pump_Button.DataBindings.Add(dynamicBinding8);
            this.m_DynamicBindings.Add(dynamicBinding8);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding9 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Manual_Washing_Pump"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Washing_Gun_Button.DataBindings.Add(dynamicBinding9);
            this.m_DynamicBindings.Add(dynamicBinding9);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding10 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Background", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Manual_Washing_Pump"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf4);
            this.m_Washing_Gun_Button.DataBindings.Add(dynamicBinding10);
            this.m_DynamicBindings.Add(dynamicBinding10);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding11 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Pressure_Input"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric1.DataBindings.Add(dynamicBinding11);
            this.m_DynamicBindings.Add(dynamicBinding11);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding12 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.PressureCalibrationValue"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric2.DataBindings.Add(dynamicBinding12);
            this.m_DynamicBindings.Add(dynamicBinding12);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding13 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.PressureCalibrationCounter"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric3.DataBindings.Add(dynamicBinding13);
            this.m_DynamicBindings.Add(dynamicBinding13);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding14 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.CleaningCounter"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric5.DataBindings.Add(dynamicBinding14);
            this.m_DynamicBindings.Add(dynamicBinding14);
        }
    }
}
