//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	
	
	public partial class Tags : Neo.ApplicationFramework.Tools.OpcClient.GlobalController, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage
	{
		
		public Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem SystemTagDay;
		
		public Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem SystemTagHour;
		
		public Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem SystemTagMinute;
		
		public Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem SystemTagYear;
		
		public Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem SystemTagMonth;
		
		public Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem SystemTagSecond;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Emergency_Stop;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Yellow_Light;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Red_Light;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Phase_Error;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Washing_Thermic;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Manuel_Washing_Thermic;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Blower_Error;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag AirHeater_Error;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Green_Light;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Buzzer;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Washing_Pump;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Manual_Washing_Pump;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Blower;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Water_Heater;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Air_Heater;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Door_Open;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Door_Close;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Piston_Up;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Piston_Down;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Pressure_Valve;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Interior_Lightning;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Washing_Time;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Company_Name;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Water_Temp_Set;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Water_Temp_Current;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Pressure_Info;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Cycle_Info;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Serial_No;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Client_No;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Drying_Time;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Automatic_Washing;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Testing_Proc;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Drying_Proc;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Dirty_Filter;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Clogged_Filter;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Clean_Filter;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Max_Pressure;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem TestTimer;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem WashTimer;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Printer;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem DryingTimer;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem LeisterStarter;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem CycleTimer;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem BlinkTimer;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem InCycle;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem InCycleTimer;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem LoopCounter;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem BuzzerTimer;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Current_Air_Heater;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Air_Heater_Set;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem prewashWaterTime;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem prewashRestTime;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem dryingAirTime;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem dryingRestTime;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem cleaningWaterTime;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem cleaningPressTime;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem cleaningRestTime;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ViewerControl;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem TestTime;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Manuel_Washing;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Man_Pre_Wash_Cycle;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem ManWash_Dry_Cycle;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem ManWashTimer;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem ManWashTime;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag DoorSafetyButton;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem MagneticDoorSwitch;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem WaterLevelSwitch;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag SafetyRelay2_LightCurtain;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Pressure_Input;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem PressureCalibrationValue;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem PressureCalibrationCounter;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag x0;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Foot_Switch;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem PausedStatus;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem WaterTransmitter;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem AirHeaterTransmitter;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag SystemLanguage;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem DPF_CAT;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem CleaningCounter;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem CleaningCounterLimit;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup1;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup2;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup3;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup4;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup5;
		
		public Tags()
		{
			this.InitializeComponent();
			this.ApplyLanguageInternal();
		}
		
		private void InitializeComponent()
		{
			this.InitializeObjectCreations();
			this.InitializeBeginInits();
			this.InitializeObjects();
			this.InitializeEndInits();
			this.ConnectDataBindings();
		}
		
		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		public virtual void ConnectDataBindings()
		{
		}
		
		private void InitializeObjectCreations()
		{
			this.SystemTagDay = new Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem("Day", "SystemTagDay", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "Day component of current date", ((short)(1)), "", "");
			this.SystemTagHour = new Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem("Hour", "SystemTagHour", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "Hour component of current time", ((short)(1)), "", "");
			this.SystemTagMinute = new Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem("Minute", "SystemTagMinute", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "Minute component of current time", ((short)(1)), "", "");
			this.SystemTagYear = new Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem("Year", "SystemTagYear", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "Year component of current date", ((short)(1)), "", "");
			this.SystemTagMonth = new Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem("Month", "SystemTagMonth", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "Month component of current date", ((short)(1)), "", "");
			this.SystemTagSecond = new Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem("Second", "SystemTagSecond", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "Second component of current time", ((short)(1)), "", "");
			this.Emergency_Stop = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Emergency_Stop", "Controller2.DataItem1", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.Yellow_Light = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Yellow_Light", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.Red_Light = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Red_Light", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.Phase_Error = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Phase_Error", "Controller2.DataItem4", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.Washing_Thermic = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Washing_Thermic", "Controller2.DataItem5", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.Manuel_Washing_Thermic = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Manuel_Washing_Thermic", "Controller2.DataItem6", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.Blower_Error = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Blower_Error", "Controller2.DataItem7", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.AirHeater_Error = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("AirHeater_Error", "Controller2.DataItem8", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.Green_Light = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Green_Light", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.Buzzer = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Buzzer", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.Washing_Pump = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Washing_Pump", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.Manual_Washing_Pump = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Manual_Washing_Pump", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.Blower = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Blower", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.Water_Heater = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Water_Heater", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.Air_Heater = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Air_Heater", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.Door_Open = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Door_Open", "Controller2.DataItem16", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.Door_Close = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Door_Close", "Controller2.DataItem17", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.Piston_Up = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Piston_Up", "Controller2.DataItem18", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.Piston_Down = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Piston_Down", "Controller2.DataItem26", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.Pressure_Valve = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Pressure_Valve", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.Interior_Lightning = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Interior_Lightning", "Controller2.DataItem28", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.Washing_Time = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Washing_Time", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), "", ((short)(1)), "", "");
			this.Company_Name = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Company_Name", "Controller2.DataItem19", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_STRING)), false, "", null);
			this.Water_Temp_Set = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Water_Temp_Set", "Controller2.DataItem30", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.Water_Temp_Current = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Water_Temp_Current", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), "", ((short)(1)), "", "");
			this.Pressure_Info = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Pressure_Info", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.Cycle_Info = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Cycle_Info", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.Serial_No = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Serial_No", "Controller2.DataItem34", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.Client_No = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Client_No", "Controller2.DataItem35", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_STRING)), false, "", null);
			this.Drying_Time = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Drying_Time", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.Automatic_Washing = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Automatic_Washing", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), "", ((short)(1)), "", "");
			this.Testing_Proc = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Testing_Proc", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), "", ((short)(1)), "", "");
			this.Drying_Proc = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Drying_Proc", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), "", ((short)(1)), "", "");
			this.Dirty_Filter = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Dirty_Filter", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), "", ((short)(1)), "", "");
			this.Clogged_Filter = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Clogged_Filter", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), "", ((short)(1)), "", "");
			this.Clean_Filter = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Clean_Filter", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), "", ((short)(1)), "", "");
			this.Max_Pressure = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Max_Pressure", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.TestTimer = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("TestTimer", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.WashTimer = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("WashTimer", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.Printer = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Printer", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), "", ((short)(1)), "", "");
			this.DryingTimer = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("DryingTimer", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.LeisterStarter = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("LeisterStarter", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.CycleTimer = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("CycleTimer", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.BlinkTimer = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("BlinkTimer", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.InCycle = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("InCycle", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.InCycleTimer = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("InCycleTimer", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.LoopCounter = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("LoopCounter", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.BuzzerTimer = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("BuzzerTimer", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.Current_Air_Heater = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Current_Air_Heater", "Controller2.DataItem33", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), false, "", null);
			this.Air_Heater_Set = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Air_Heater_Set", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.prewashWaterTime = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("prewashWaterTime", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.prewashRestTime = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("prewashRestTime", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.dryingAirTime = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("dryingAirTime", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.dryingRestTime = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("dryingRestTime", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.cleaningWaterTime = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("cleaningWaterTime", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.cleaningPressTime = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("cleaningPressTime", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.cleaningRestTime = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("cleaningRestTime", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.ViewerControl = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ViewerControl", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.TestTime = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("TestTime", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.Manuel_Washing = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Manuel_Washing", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), "", ((short)(1)), "", "");
			this.Man_Pre_Wash_Cycle = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Man_Pre_Wash_Cycle", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.ManWash_Dry_Cycle = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("ManWash_Dry_Cycle", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.ManWashTimer = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("ManWashTimer", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.ManWashTime = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("ManWashTime", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.DoorSafetyButton = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("DoorSafetyButton", "Controller2.DataItem37", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.MagneticDoorSwitch = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("MagneticDoorSwitch", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), "", ((short)(1)), "", "");
			this.WaterLevelSwitch = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("WaterLevelSwitch", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), "", ((short)(1)), "", "");
			this.SafetyRelay2_LightCurtain = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("SafetyRelay2_LightCurtain", "Controller2.DataItem41", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.Pressure_Input = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Pressure_Input", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.PressureCalibrationValue = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("PressureCalibrationValue", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Write, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.PressureCalibrationCounter = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("PressureCalibrationCounter", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.x0 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("x0", "Controller2.DataItem44", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.Foot_Switch = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Foot_Switch", "Controller2.DataItem45", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.PausedStatus = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("PausedStatus", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), "", ((short)(1)), "", "");
			this.WaterTransmitter = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("WaterTransmitter", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.AirHeaterTransmitter = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("AirHeaterTransmitter", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.SystemLanguage = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("SystemLanguage", "Controller2.DataItem59", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.DPF_CAT = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("DPF_CAT", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), "", ((short)(1)), "", "");
			this.CleaningCounter = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("CleaningCounter", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.CleaningCounterLimit = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("CleaningCounterLimit", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.PollGroup1 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup2 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup3 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup4 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup5 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
		}
		
		private void InitializeBeginInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
		}
		
		private void InitializeEndInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).EndInit();
		}
		
		private void InitializeObjects()
		{
			this.SystemTagDay.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(new Neo.ApplicationFramework.Interfaces.VariantValue("0"), 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem20"}, true));
			this.SystemTagHour.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(new Neo.ApplicationFramework.Interfaces.VariantValue("0"), 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem21"}, true));
			this.SystemTagMinute.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(new Neo.ApplicationFramework.Interfaces.VariantValue("0"), 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem22"}, true));
			this.SystemTagYear.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(new Neo.ApplicationFramework.Interfaces.VariantValue("0"), 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem23"}, true));
			this.SystemTagMonth.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(new Neo.ApplicationFramework.Interfaces.VariantValue("0"), 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem24"}, true));
			this.SystemTagSecond.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(new Neo.ApplicationFramework.Interfaces.VariantValue("0"), 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem25"}, true));
			this.Yellow_Light.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem3"}, true));
			this.Red_Light.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem2"}, true));
			this.Green_Light.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem9"}, true));
			this.Buzzer.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem10"}, true));
			this.Washing_Pump.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem11"}, true));
			this.Manual_Washing_Pump.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem12"}, true));
			this.Blower.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem13"}, true));
			this.Water_Heater.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem14"}, true));
			this.Air_Heater.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem15"}, true));
			this.Pressure_Valve.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem27"}, true));
			this.Washing_Time.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.Water_Temp_Current.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem31"}, true));
			this.Pressure_Info.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem32"}, true));
			this.Cycle_Info.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.Drying_Time.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.Automatic_Washing.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.Testing_Proc.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.Drying_Proc.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.Dirty_Filter.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.Clogged_Filter.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.Clean_Filter.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.Max_Pressure.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem29"}, true));
			this.TestTimer.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.WashTimer.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.Printer.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem39"}, true));
			this.DryingTimer.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.LeisterStarter.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.CycleTimer.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.BlinkTimer.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.InCycle.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.InCycleTimer.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.LoopCounter.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.BuzzerTimer.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.Air_Heater_Set.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem36"}, true));
			this.prewashWaterTime.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem49"}, true));
			this.prewashRestTime.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem50"}, true));
			this.dryingAirTime.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem51"}, true));
			this.dryingRestTime.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem52"}, true));
			this.cleaningWaterTime.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem53"}, true));
			this.cleaningPressTime.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem54"}, true));
			this.cleaningRestTime.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem55"}, true));
			this.TestTime.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem58"}, true));
			this.Manuel_Washing.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.Man_Pre_Wash_Cycle.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem56"}, true));
			this.ManWash_Dry_Cycle.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem57"}, true));
			this.ManWashTimer.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.ManWashTime.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.MagneticDoorSwitch.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem38"}, true));
			this.WaterLevelSwitch.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem40"}, true));
			this.Pressure_Input.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem42"}, true));
			this.PressureCalibrationValue.AccessRights.Add("Controller2", Core.Api.DataSource.AccessRights.Write);
			this.PressureCalibrationValue.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem43"}, true));
			this.PressureCalibrationCounter.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.PausedStatus.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem46"}, true));
			this.WaterTransmitter.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem47"}, true));
			this.AirHeaterTransmitter.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem48"}, true));
			this.DPF_CAT.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.CleaningCounter.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem60"}, true));
			this.CleaningCounterLimit.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller2"}, new string[] {
							"DataItem61"}, true));
			this.GlobalDataItems.Add(this.SystemTagDay);
			this.GlobalDataItems.Add(this.SystemTagHour);
			this.GlobalDataItems.Add(this.SystemTagMinute);
			this.GlobalDataItems.Add(this.SystemTagYear);
			this.GlobalDataItems.Add(this.SystemTagMonth);
			this.GlobalDataItems.Add(this.SystemTagSecond);
			this.LightweightTags.Add(this.Emergency_Stop);
			this.GlobalDataItems.Add(this.Yellow_Light);
			this.GlobalDataItems.Add(this.Red_Light);
			this.LightweightTags.Add(this.Phase_Error);
			this.LightweightTags.Add(this.Washing_Thermic);
			this.LightweightTags.Add(this.Manuel_Washing_Thermic);
			this.LightweightTags.Add(this.Blower_Error);
			this.LightweightTags.Add(this.AirHeater_Error);
			this.GlobalDataItems.Add(this.Green_Light);
			this.GlobalDataItems.Add(this.Buzzer);
			this.GlobalDataItems.Add(this.Washing_Pump);
			this.GlobalDataItems.Add(this.Manual_Washing_Pump);
			this.GlobalDataItems.Add(this.Blower);
			this.GlobalDataItems.Add(this.Water_Heater);
			this.GlobalDataItems.Add(this.Air_Heater);
			this.LightweightTags.Add(this.Door_Open);
			this.LightweightTags.Add(this.Door_Close);
			this.LightweightTags.Add(this.Piston_Up);
			this.LightweightTags.Add(this.Piston_Down);
			this.GlobalDataItems.Add(this.Pressure_Valve);
			this.LightweightTags.Add(this.Interior_Lightning);
			this.GlobalDataItems.Add(this.Washing_Time);
			this.LightweightTags.Add(this.Company_Name);
			this.LightweightTags.Add(this.Water_Temp_Set);
			this.GlobalDataItems.Add(this.Water_Temp_Current);
			this.GlobalDataItems.Add(this.Pressure_Info);
			this.GlobalDataItems.Add(this.Cycle_Info);
			this.LightweightTags.Add(this.Serial_No);
			this.LightweightTags.Add(this.Client_No);
			this.GlobalDataItems.Add(this.Drying_Time);
			this.GlobalDataItems.Add(this.Automatic_Washing);
			this.GlobalDataItems.Add(this.Testing_Proc);
			this.GlobalDataItems.Add(this.Drying_Proc);
			this.GlobalDataItems.Add(this.Dirty_Filter);
			this.GlobalDataItems.Add(this.Clogged_Filter);
			this.GlobalDataItems.Add(this.Clean_Filter);
			this.GlobalDataItems.Add(this.Max_Pressure);
			this.GlobalDataItems.Add(this.TestTimer);
			this.GlobalDataItems.Add(this.WashTimer);
			this.GlobalDataItems.Add(this.Printer);
			this.GlobalDataItems.Add(this.DryingTimer);
			this.GlobalDataItems.Add(this.LeisterStarter);
			this.GlobalDataItems.Add(this.CycleTimer);
			this.GlobalDataItems.Add(this.BlinkTimer);
			this.GlobalDataItems.Add(this.InCycle);
			this.GlobalDataItems.Add(this.InCycleTimer);
			this.GlobalDataItems.Add(this.LoopCounter);
			this.GlobalDataItems.Add(this.BuzzerTimer);
			this.LightweightTags.Add(this.Current_Air_Heater);
			this.GlobalDataItems.Add(this.Air_Heater_Set);
			this.GlobalDataItems.Add(this.prewashWaterTime);
			this.GlobalDataItems.Add(this.prewashRestTime);
			this.GlobalDataItems.Add(this.dryingAirTime);
			this.GlobalDataItems.Add(this.dryingRestTime);
			this.GlobalDataItems.Add(this.cleaningWaterTime);
			this.GlobalDataItems.Add(this.cleaningPressTime);
			this.GlobalDataItems.Add(this.cleaningRestTime);
			this.LightweightTags.Add(this.ViewerControl);
			this.GlobalDataItems.Add(this.TestTime);
			this.GlobalDataItems.Add(this.Manuel_Washing);
			this.GlobalDataItems.Add(this.Man_Pre_Wash_Cycle);
			this.GlobalDataItems.Add(this.ManWash_Dry_Cycle);
			this.GlobalDataItems.Add(this.ManWashTimer);
			this.GlobalDataItems.Add(this.ManWashTime);
			this.LightweightTags.Add(this.DoorSafetyButton);
			this.GlobalDataItems.Add(this.MagneticDoorSwitch);
			this.GlobalDataItems.Add(this.WaterLevelSwitch);
			this.LightweightTags.Add(this.SafetyRelay2_LightCurtain);
			this.GlobalDataItems.Add(this.Pressure_Input);
			this.GlobalDataItems.Add(this.PressureCalibrationValue);
			this.GlobalDataItems.Add(this.PressureCalibrationCounter);
			this.LightweightTags.Add(this.x0);
			this.LightweightTags.Add(this.Foot_Switch);
			this.GlobalDataItems.Add(this.PausedStatus);
			this.GlobalDataItems.Add(this.WaterTransmitter);
			this.GlobalDataItems.Add(this.AirHeaterTransmitter);
			this.LightweightTags.Add(this.SystemLanguage);
			this.GlobalDataItems.Add(this.DPF_CAT);
			this.GlobalDataItems.Add(this.CleaningCounter);
			this.GlobalDataItems.Add(this.CleaningCounterLimit);
			this.PollGroup1.Interval = 500;
			this.PollGroup1.Name = "PollGroup1";
			this.PollGroup2.Interval = 500;
			this.PollGroup2.Name = "PollGroup2";
			this.PollGroup3.Interval = 500;
			this.PollGroup3.Name = "PollGroup3";
			this.PollGroup4.Interval = 500;
			this.PollGroup4.Name = "PollGroup4";
			this.PollGroup5.Interval = 500;
			this.PollGroup5.Name = "PollGroup5";
			this.PollGroups.Add(this.PollGroup1);
			this.PollGroups.Add(this.PollGroup2);
			this.PollGroups.Add(this.PollGroup3);
			this.PollGroups.Add(this.PollGroup4);
			this.PollGroups.Add(this.PollGroup5);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Tags));
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage()
		{
			this.ApplyLanguage();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected virtual void ApplyLanguage()
		{
			this.ApplyLanguageInternal();
		}
	}
}
